### ISSUE TITLE
[ADMIN SITE][COMMON] Lỗi request khi nhập 

### ISSUE THREAD

**Issue by baonh201092** [LeDangIUH/Project-FTA#100]
Step:
1/ Đăng Nhập FTA bằng account spadmin - xxx.
2/ Click User -> Hồ Sơ Cá Nhân.
3/ Nhập dữ liệu cho textbox [Địa chỉ] như hình.
4/ Click Lưu.
# BUG common cho tất cả các textbox có thể nhập dữ liệu bất kỳ, nên mọi người check lại tất cả để fix chung luôn.

Picture 1:
![bug003_1](https://cloud.githubusercontent.com/assets/5047540/18483596/e3f442d8-7a0e-11e6-9771-7ee7e4c93e57.PNG)

Picture 2:
![bug003_2](https://cloud.githubusercontent.com/assets/5047540/18483413/1c9ad030-7a0e-11e6-93ae-0f3beeed142a.PNG)

**Comment by lyquoclam** [comment]
@baonh201092 
Anh bảo em fixed rồi nha đế tối nay anh Dang build roi mới test nha

**Comment by baonh201092** [comment]
Reviewed OK
