### ISSUE TITLE
[ADMIN SITE] Không giới hạn khi nhập bình luận

### ISSUE THREAD

**Issue by nhanchuan** [LeDangIUH/Project-FTA#101]
1/ Đăng Nhập FTA bằng account chuan01 - 123.
2/ Trang chủ -> BÌNH LUẬN / ĐÁNH GIÁ SẢN PHẨM.
 Nhập nội dung: ádgehstnrsngthmxbqwvt ádgehstnrsngthmxbqwvt ádgehstnrsngthmxbqwvt ádgehstnrsngthmxbqwvt ádgehstnrsngthmxbqwvt ádgehstnrsngthmxbqwvt ádgehstnrsngthmxbqwvt ádgehstnrsngthmxbqwvt ádgehstnrsngthmxbqwvt……

![image](https://cloud.githubusercontent.com/assets/15918548/18483811/fc7b82c0-7a0f-11e6-9799-247a88e7c944.png)

**Comment by nhanchuan** [comment]
- Nhập xong Submit. đơ máy luôn 👎

**Comment by nhanchuan** [comment]
- Tương tự các trường nhập khác đều không có giới hạn

**Comment by nhanchuan** [comment]
![image](https://cloud.githubusercontent.com/assets/15918548/18484181/97c3892a-7a11-11e6-8597-009836ab0b0c.png)

**Comment by khaiho2002** [comment]
Lâm sửa cái này nha

**Comment by lyquoclam** [comment]
đã hạn chế ký tự cho tất cả input từ user1 đến user5

**Comment by lyquoclam** [comment]
đã hạn chế số ký tự input cho all users

**Comment by nhanchuan** [comment]
- review OK
