### ISSUE TITLE
[ADMIN SITE] Radio chặn quảng cáo được hiển thị hay sử dụng ở đâu

### ISSUE THREAD

**Issue by baonh201092** [LeDangIUH/Project-FTA#103]
Picture:
![ques001](https://cloud.githubusercontent.com/assets/5047540/18484500/e6ad6e2e-7a12-11e6-8420-f020ea482381.PNG)

**Comment by lyquoclam** [comment]
Lâm fix ticket này nha

**Comment by lyquoclam** [comment]
Hi @baonh201092 ,

Tạo quảng cáo ở user loại company
1. Đăng nhập user loại Company.
2. Chọn Quảng Bả Sản Phẩm ở menu bên trái.
3. Chọn nút Thêm Quảng Cáo để thêm quảng cáo.
4. Sau khi thêm quảng cáo quay lại bước 2, sau đó nhấn nút Gửi đến user loại user.

**Note:** Quảng cáo này chỉ gửi đến các users thuộc loại user. Còn các user loại SuperAdmin, Admin, Supervisor and Company sẽ ko nhận quảng cáo này

**Comment by baonh201092** [comment]
Ok Clear.
Nhưng mà nếu được thì nên design lại bảng thông tin quảng cáo ở User5. Nhìn có vẻ chuối quá.
![bug028](https://cloud.githubusercontent.com/assets/5047540/18683767/d8fb36f6-7f9b-11e6-9eb8-acffda41625e.PNG)

**Comment by baonh201092** [comment]
closed
