### ISSUE TITLE
[ADMIN SITE] Đưa từ ngữ sai chính tả lên website + Tiếng Anh Việt lẫn lộn

### ISSUE THREAD

**Issue by nhanchuan** [LeDangIUH/Project-FTA#105]
![image](https://cloud.githubusercontent.com/assets/15918548/18484849/5d3c3c86-7a14-11e6-8045-955f0a399968.png)

**Comment by khaiho2002** [comment]
Lâm sửa cái này nha

**Comment by lyquoclam** [comment]
Fixed at Revision #548

**Comment by nhanchuan** [comment]
- review OK
