### ISSUE TITLE
[ADMIN SITE] Chi tiết thừa trên website

### ISSUE THREAD

**Issue by nhanchuan** [LeDangIUH/Project-FTA#106]
![image](https://cloud.githubusercontent.com/assets/15918548/18484984/1462fa12-7a15-11e6-9878-05600eed7afd.png)

**Comment by khaiho2002** [comment]
Lâm sửa cái này nha

**Comment by lyquoclam** [comment]
Fixed at Revision #548

**Comment by nhanchuan** [comment]
- Review OK
