### ISSUE TITLE
[ADMIN SITE] Không Validation khi upload Avatar không đúng định dạng ảnh

### ISSUE THREAD

**Issue by nhanchuan** [LeDangIUH/Project-FTA#107]
![image](https://cloud.githubusercontent.com/assets/15918548/18485216/18b4fa06-7a16-11e6-8f7a-f889b1e2f30e.png)

**Comment by lyquoclam** [comment]
### Fixed at trang HoSoCaNhan của chức năng uploading avatar image

**Comment by nhanchuan** [comment]
- Vẫn còn bị lỗi khi Upload file không đúng định dạng
  ![image](https://cloud.githubusercontent.com/assets/15918548/18617600/67aba78c-7dfd-11e6-9c2e-3406565db08f.png)

**Comment by baonh201092** [comment]
@lyquoclam . Vẫn còn nha. Nếu load file khác loại ảnh thì hiển thị ảnh cũ (nếu có), hoặc ảnh mặc định.

**Comment by lyquoclam** [comment]
Anh @baonh201092 
bị ở trang nào anh Bảo

**Comment by baonh201092** [comment]
@lyquoclam . hồ sơ cá nhân thôi Lâm.
Check luôn cho các phần upload ảnh tương tự nha.

**Comment by lyquoclam** [comment]
Em đã thêm validation cho chọn file. Đợi build 25/9
