### ISSUE TITLE
[ADMIN SITE] Có thể dùng 1 email để đăng ký không giới hạn số Tài khoản người dùng

### ISSUE THREAD

**Issue by nhanchuan** [LeDangIUH/Project-FTA#109]
1/ Đăng Nhập FTA bằng account chuan01 - 123.
2/ Hồ sơ cá nhân.
3/ Thay đổi email
=> Lưu

=> Tiếp tục sử dụng Email củ để đăng ký.

=> Quay lại bước 2.

![image](https://cloud.githubusercontent.com/assets/15918548/18486006/83a297c6-7a19-11e6-811f-e81dfe4a8d1d.png)

![image](https://cloud.githubusercontent.com/assets/15918548/18486032/aadf8c0e-7a19-11e6-92d8-c8a638325a56.png)

**Comment by nhanchuan** [comment]
- Vẫn còn nhé @khaiho2002 
  sữa Email trong Tài khoản củ, rồi dùng email đó DK mới vẫ dc nhé.
  ![image](https://cloud.githubusercontent.com/assets/15918548/18609504/e810de18-7d2d-11e6-826d-1c13631db9a8.png)

**Comment by khaiho2002** [comment]
Sửa ở phiên bản 574 
- Chặn không cho edit email đối với user.
- Cho edit email đối với tài khoản quản trị, tài khoản giám sát, user công ty (User nội bộ)

**Comment by nhanchuan** [comment]
- Review OK
