### ISSUE TITLE
[BUG] Báo lỗi khi sửa thông tin [Privacy Policy], [Term Of Service]

### ISSUE THREAD

**Issue by baonh201092** [LeDangIUH/Project-FTA#11]
1/ Login trang Admin (User = admin, pass = zxcvbnm)
2/ Click [Setting] -> [Privacy Policy] -> Sửa nội dung -> Click [Save Policy]
=> Báo lỗi "Error! System.UnauthorizedAccessException: Access to the path 'E:\FTA\Deploy\Thucphamminhbach\Policy\PrivacyPolicyVN.txt' is denied. at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath) at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath) at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy) at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options) at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize) at System.IO.StreamWriter..ctor(String path, Boolean append) at System.IO.File.CreateText(String path) at Admin_Pages_PrivacyPolicy.btnSave_Click(Object sender, EventArgs e) in e:\FTA\Deploy\Thucphamminhbach\Admin\Pages\PrivacyPolicy.aspx.cs:line 65"

Picture:
![bug024](https://cloud.githubusercontent.com/assets/5047540/17838454/3e028e8e-67f8-11e6-95c6-84045a7839a9.PNG)

**Comment by nhanchuan** [comment]
1/Access vào trang http://linhkien3h.com/Admin/Pages/PrivacyPolicy.aspx
user name: admin
pass: zxcvbnm
2/ Click [Setting] -> [Privacy Policy] -> Sửa nội dung -> Click [Save Policy]

**Comment by baonh201092** [comment]
Reviewed OK
