### ISSUE TITLE
[ADMIN SITE] Ngày sinh lớn hơn ngày hiện tại

### ISSUE THREAD

**Issue by nhanchuan** [LeDangIUH/Project-FTA#110]
![image](https://cloud.githubusercontent.com/assets/15918548/18486286/c7c1a5e0-7a1a-11e6-8a8a-dab59b942ca4.png)

**Comment by khaiho2002** [comment]
Sửa ở phiên bản 555

**Comment by nhanchuan** [comment]
- Review OK
