### ISSUE TITLE
[ADMIN SITE] Có nhiều Scroll  trong 1 vùng nội dung

### ISSUE THREAD

**Issue by nhanchuan** [LeDangIUH/Project-FTA#111]
![image](https://cloud.githubusercontent.com/assets/15918548/18486525/9acb0e86-7a1b-11e6-8af8-79a7a2c37bf1.png)

**Comment by nhanchuan** [comment]
- Vẫn còn nha @lyquoclam 
  ![image](https://cloud.githubusercontent.com/assets/15918548/18609434/38156106-7d2c-11e6-94ea-04b5382e06a6.png)

**Comment by nhanchuan** [comment]
**Vấn đề**
Nếu như có rất nhiều bình luận trên sản phẩm thì Cứ Scroll toàn bộ sẽ không ổn.
Vì vậy có thể nâng cấp thêm tính năng  => "Xem thêm bình luận" trên mỗi sản phẩm. Và cho giới hạn số bình luận hiện ra là Từ 3 - 10, tùy theo trong Setting.

**Gợi ý**

![image](https://cloud.githubusercontent.com/assets/15918548/18616092/0642e39c-7de0-11e6-84ff-89d217c447a5.png)

**Comment by baonh201092** [comment]
Load tất cả bình luận => Nên suy nghĩ vấn đề performance
