### ISSUE TITLE
[ADMIN SITE] Tháng Đầu lớn hơn Tháng Sau

### ISSUE THREAD

**Issue by baonh201092** [LeDangIUH/Project-FTA#112]
Step:
1/ Đăng Nhập FTA bằng account spadmin - xxx.
2/ Chọn tháng đầu 7, tháng sau 1.
3/ Click Lọc.

Suggestion:
- Cho load tháng đầu trước, load tháng sau >= tháng đầu.

Picture:
![bug004](https://cloud.githubusercontent.com/assets/5047540/18515936/474efb7c-7ac1-11e6-82bf-d0be06c03c41.PNG)

**Comment by khaiho2002** [comment]
Sửa ở phiên bản 555

**Comment by vdhung** [comment]
fix lai

**Comment by baonh201092** [comment]
Reviewed OK
