### ISSUE TITLE
[ADMIN SITE] Gửi y/c nâng cấp tài khoản công ty thành công nhưng không thấy y/c nâng cấp

### ISSUE THREAD

**Issue by nhanchuan** [LeDangIUH/Project-FTA#115]
1/ Login Admin FTA 
user : chuanx
2/ Thực hiện nhập và gửi y/c nâng cấp Tài khoản công ty
3/ Hệ thống báo cập nhật thành công
4/ Login Admin FTA
user : spadmin => Để kiểm tra
5/ Vào Hồ sơ đăng ký
=> KQ: không thấy Y/c mới.

**Comment by nhanchuan** [comment]
![image](https://cloud.githubusercontent.com/assets/15918548/18520459/195fefee-7ad2-11e6-9d0e-1564f6df821e.png)

**Comment by khaiho2002** [comment]
Phải 1 ngày kể từ ngày submit mới thấy
