### ISSUE TITLE
[ADMIN SITE] Giới tính mặc định là Nữ, không change thành Nam được

### ISSUE THREAD

**Issue by baonh201092** [LeDangIUH/Project-FTA#118]
Step:
1/ Đăng Nhập FTA bằng account spadmin - xxx.
2/ Click Tạo, hoặc Chỉnh Sửa User
3/ Chọn giới tính Nam => Lưu
=> Không thể thay đổi thành Nam, chỉ là Nữ thôi. Nhọ

Picture:
![bug007_1](https://cloud.githubusercontent.com/assets/5047540/18557402/ff14816e-7b98-11e6-8c7b-f3a755ac6391.PNG)

**Comment by khaiho2002** [comment]
Sửa trong phiên bản #547

**Comment by baonh201092** [comment]
Reviewed OK
