### ISSUE TITLE
[ADMIN SITE] Doanh nghiệp có thể Like và đánh giá sản phẩm của mình

### ISSUE THREAD

**Issue by nhanchuan** [LeDangIUH/Project-FTA#119]
1/ Access http://admin.thucphamminhbach.org
- Acc: chuanx
  2/ Nhập barcode sản phẩm của chính Doanh nghiệp vào TextBox tra cứu
  => Kết quả sản phẩm
  3/ Nhấn Like và đánh giá 5 sao

![image](https://cloud.githubusercontent.com/assets/15918548/18559289/d5df9876-7ba0-11e6-970f-a8b65f9a0191.png)

**Comment by khaiho2002** [comment]
Sửa tại phiên bản #545
Note: Danh nghiệp có thể yêu thích sản phẩm của mình

**Comment by nhanchuan** [comment]
- Review OK
