### ISSUE TITLE
[BUG] Không cần upload ảnh lại một lần nữa

### ISSUE THREAD

**Issue by baonh201092** [LeDangIUH/Project-FTA#12]
1/ Login trang Admin (User = admin, pass = zxcvbnm)
2/ Click [Photo Gallery] -> [Gallery] -> [Select] 1 ảnh -> [Edit Image Info] -> Click Update
=> Không yêu cầu upload ảnh đã được upload rồi.

Picture:
![bug025](https://cloud.githubusercontent.com/assets/5047540/17838785/4e049d34-67ff-11e6-86bf-c69f7ba233e2.PNG)

**Comment by nhanchuan** [comment]
1/ Login trang http://linhkien3h.com/Admin/Pages/PhotoLibrary.aspx (User = admin, pass = zxcvbnm)
2/ Click [Photo Gallery] -> [Gallery] -> [Select] 1 ảnh -> [Edit Image Info] -> Click Update
=> Đã fix: Có thể thay đổi ảnh khác or giữ nguyên ảnh cũ.

**Comment by baonh201092** [comment]
Reviewed OK
