### ISSUE TITLE
[ADMIN SITE] Doanh nghiệp có thể tự Report sản phẩm của mình

### ISSUE THREAD

**Issue by nhanchuan** [LeDangIUH/Project-FTA#120]
1/ Access http://admin.thucphamminhbach.org

Acc: chuanx

 2/ Nhập barcode sản phẩm của chính Doanh nghiệp vào TextBox tra cứu => Kết quả sản phẩm

![image](https://cloud.githubusercontent.com/assets/15918548/18559604/3d7086d4-7ba2-11e6-9692-8c58c9744320.png)

**Comment by khaiho2002** [comment]
Sửa ở phiên bản #545

**Comment by nhanchuan** [comment]
- Review OK
