### ISSUE TITLE
[ADMIN SITE] Không Review Hình hoặc tên hình khi chọn Hình sản phẩm

### ISSUE THREAD

**Issue by nhanchuan** [LeDangIUH/Project-FTA#122]
1/ Access http://admin.thucphamminhbach.org
Acc: chuanx
2/ Vào MEnu sản phẩm.
3/ Thêm sản phẩm mới.

![image](https://cloud.githubusercontent.com/assets/15918548/18560273/0d82c664-7ba5-11e6-8e5b-fd95d04a4072.png)

**Comment by khaiho2002** [comment]
Lâm sửa cái này nhé

**Comment by lyquoclam** [comment]
Hi @nhanchuan 

Ở đây không cần tên hình ảnh. Chỉ chọn image va show hình ảnh len thoi

**Comment by nhanchuan** [comment]
- Ok @lyquoclam : như ở trên đề cập là Review Hình hoặc Tên hình

**Comment by nhanchuan** [comment]
**\- Review : Chức năng được fix nhưng chưa hoàn chỉnh.**
Detail: 
1/ Click chọn Hình 
![image](https://cloud.githubusercontent.com/assets/15918548/18615980/a4357996-7ddd-11e6-926e-c4f99b7d35ab.png)
2/ Duyệt hình trên máy tính.
![image](https://cloud.githubusercontent.com/assets/15918548/18615998/da586236-7ddd-11e6-8618-ef2d403e5860.png)
==> Kết quả : Không thấy Review hình.
![image](https://cloud.githubusercontent.com/assets/15918548/18616001/fd49f912-7ddd-11e6-9805-679e4594376d.png)

---

THực hiện lại các thao tác trên một lần nữa mới cho kết quả.
![image](https://cloud.githubusercontent.com/assets/15918548/18616016/64ec18ac-7dde-11e6-9d02-badaecc44feb.png)

---

**TƯƠNG TỰ CHO CÁC CHỨNG NHẬN THỰC PHẨM**

**Comment by lyquoclam** [comment]
Hi @nhanchuan 

Lam va anh Khai đã test rồi show image bình thường khi chọn 1 hình ảnh đầu tiên. Chuan vui lòng test lai 1 lần nữa nha.

**Comment by lyquoclam** [comment]
Error này xảy ra ở IE. Sẽ tìm solution for IE sau

**Comment by lyquoclam** [comment]
Hi @nhanchuan 

Em Fixed roi nha. Đợi build anh Dang 3:00 AM (20-09-2016) moi test nha anh Chuan

**Comment by baonh201092** [comment]
Fix #107 cho bug này luôn

**Comment by lyquoclam** [comment]
Em đã thêm validation cho chọn file. Đợi build 25/9
