### ISSUE TITLE
[ADMIN SITE] User 5 bình luận null

### ISSUE THREAD

**Issue by baonh201092** [LeDangIUH/Project-FTA#123]
Step:
1/ Đăng Nhập FTA bằng account baonh05 - zxcvbnm.
2/ Click Bình Luận
3.1/ Nhập nội dung: <html> => nội dung trống
3.2/ Không nhập gì => hiển thị null.

Suggestion:
- Cảnh báo User nhập thông tin chính xác.

Picture 1: Bình luận ngoài trang chủ
![bug009](https://cloud.githubusercontent.com/assets/5047540/18560550/4c08ad76-7ba6-11e6-8270-a84705cb2189.PNG)

Picture 2: Bình luận trong trang sản phẩm
![bug011](https://cloud.githubusercontent.com/assets/5047540/18561776/7a4570de-7bab-11e6-81e1-5ac554a244c4.PNG)

**Comment by khaiho2002** [comment]
@Lâm fix nhé

**Comment by baonh201092** [comment]
Vẫn còn nhé em @lyquoclam 
enter nhiều dòng rồi bình luận vẫn null thôi.
Viết cái regex cho nó lọc hết rồi apply theo rule. Nhưng hiện tại enter thôi mà nó báo chỉ nhập tối đa 200 kí tự cũng ko hợp lí, phải là ko được bỏ trống nhé.

**Comment by lyquoclam** [comment]
Em đã Fixed roi đó anh Bảo @baonh201092

**Comment by baonh201092** [comment]
@lyquoclam . Check mới bình luận ngoài thôi em, vào cấp 1 là tèo.

**Comment by lyquoclam** [comment]
Em đã fixed subcomment, đợi build của anh Đăng ngày 22/9

**Comment by baonh201092** [comment]
Reviewed OK
