### ISSUE TITLE
[ADMIN SITE][QUESTION] Sắp xếp các báo cáo User dựa trên gì.

### ISSUE THREAD

**Issue by baonh201092** [LeDangIUH/Project-FTA#124]
Hiện tại thấy mỗi lần User báo cáo về là tin hiển thị vị trí khác nhau. Vậy thứ tự này dựa vào gì.
Nếu chưa có sắp xếp thì cho thứ tự theo thời gian, tin mới nhất thì ở đầu.

**Comment by khaiho2002** [comment]
@Lam fix nhé

**Comment by lyquoclam** [comment]
Hi @baonh201092 ,

Trang đó sort theo ngày tạo(Giảm dần theo ngày tạo)

**Comment by baonh201092** [comment]
"thứ tự theo thời gian, tin mới nhất thì ở đầu"

**Comment by baonh201092** [comment]
Reviewed OK
