### ISSUE TITLE
[ADMIN SITE] Tạo một chương trình khuyến mãi với giá khuyến mãi <= 0

### ISSUE THREAD

**Issue by nhanchuan** [LeDangIUH/Project-FTA#125]
1/ Access http://admin.thucphamminhbach.org
Acc: chuanx
2/ Sản phẩm
3/ Khuyễn mãi
4/ Nhập chuương trình khuyễn mãi

![image](https://cloud.githubusercontent.com/assets/15918548/18561407/eaedbb36-7ba9-11e6-929c-9ae46ca73256.png)

**Comment by khaiho2002** [comment]
Lâm fix cái này nhé

**Comment by khaiho2002** [comment]
@Lâm fix nhé

**Comment by nhanchuan** [comment]
- Giá sản phẩm âm vẫn còn được nhé @lyquoclam 
  ![image](https://cloud.githubusercontent.com/assets/15918548/18609745/faf5860e-7d33-11e6-9614-a96fe0f4ba7e.png)

**Comment by lyquoclam** [comment]
@nhanchuan 
Lam fixed roi nha. để tối nay anh Dang build roi test nha Chuan

**Comment by baonh201092** [comment]
@lyquoclam . giờ không thêm được luôn nha Lâm.

**Comment by lyquoclam** [comment]
Fixed, Đợi build 25/9
