### ISSUE TITLE
[ADMIN SITE] Table hiển thị vượt range

### ISSUE THREAD

**Issue by baonh201092** [LeDangIUH/Project-FTA#126]
Step:
1/ Đăng Nhập FTA bằng account spadmin - xxx.
2/ Click Báo Cáo Sản Phẩm

Suggestion:
# \- Fix cho toàn bộ các table khác hiển thị tương tự.

Picture:
![bug010](https://cloud.githubusercontent.com/assets/5047540/18561467/24ebe36c-7baa-11e6-9691-576ef57fe9c4.PNG)

**Comment by LeDangIUH** [comment]
@lâm em coi lại..hiện tại vẫn lỗi..cần rà sót tòn bộ màn hình.

**Comment by baonh201092** [comment]
Reviewed OK
