### ISSUE TITLE
[ADMIN SITE] Xử lý logic nhập nhằng

### ISSUE THREAD

**Issue by baonh201092** [LeDangIUH/Project-FTA#127]
Step:
1/ Đăng Nhập FTA bằng account spadmin - xxx.
2/ Click Hồ Sơ Đăng Ký
3/ Xem hồ sơ
4/ Chuyển => user => chuyển

Suggestion:
- Tại sao phải thông báo spadmin nhập trả lời trong khi đã hiện popup lên rồi, như thế rất bất tiện. Chỉ cần check xem sau khi click button chuyển, user đã nhập trả lời chưa, nếu chưa thì yêu cầu nhập là được.

Picture:
![bug012](https://cloud.githubusercontent.com/assets/5047540/18562049/6f0959fa-7bac-11e6-965b-7df4e952f1b9.PNG)

**Comment by khaiho2002** [comment]
Lâm fix cái này nhé

**Comment by lyquoclam** [comment]
Em dang fix bug này nha đừng đụng vào nha

**Comment by baonh201092** [comment]
Reviewed OK
