### ISSUE TITLE
[ADMIN SITE] Nâng cấp Tính năng Lịch sử tra cứu

### ISSUE THREAD

**Issue by nhanchuan** [LeDangIUH/Project-FTA#131]
*\* Suggestion : 
     - Hiển thị dạng List
![image](https://cloud.githubusercontent.com/assets/15918548/18606001/25f4fc30-7ccc-11e6-9181-5e058cc62849.png)
- Clear History
  ![image](https://cloud.githubusercontent.com/assets/15918548/18606006/4f67674c-7ccc-11e6-80d0-918f590301f0.png)

**Comment by vdhung** [comment]
ko cần nâng cấp... theo design.
