### ISSUE TITLE
[ADMIN SITE] Kiểm tra user baonh05 thuộc User nào.

### ISSUE THREAD

**Issue by baonh201092** [LeDangIUH/Project-FTA#132]
1/ Đăng nhập bằng User baonh05:zxcvbnm
=> Kiểm tra user này thuộc loại User nào. Data liên quan User này bị lỗi hoàn toàn.

Picture 1:
![bug012](https://cloud.githubusercontent.com/assets/5047540/18612855/0fb91be4-7d90-11e6-83c9-2f472c3a5c8a.PNG)

Picture 2:
![bug012_1](https://cloud.githubusercontent.com/assets/5047540/18612856/18090ae8-7d90-11e6-8b86-8af8c154e0cd.PNG)

**Comment by baonh201092** [comment]
@vdhung Fix là như thế nào Hưng.

**Comment by vdhung** [comment]
Build bản mới rồi test lại @@

**Comment by baonh201092** [comment]
Reviewed OK
