### ISSUE TITLE
[ADMIN SITE] Sai lệnh cột number trên table

### ISSUE THREAD

**Issue by LeDangIUH** [LeDangIUH/Project-FTA#133]
![image](https://cloud.githubusercontent.com/assets/3908468/18612957/feb48a12-7d95-11e6-9bce-bc5ea5bbf504.png)

Cần rà sót toàn bộ các page

**Comment by vdhung** [comment]
@khaiho2002  mấy cột STT ko dùng width: 1% --> chuyển thành 10% or ko set

**Comment by baonh201092** [comment]
Reviewed OK
