### ISSUE TITLE
[ADMIN SITE] Không tạo được User

### ISSUE THREAD

**Issue by baonh201092** [LeDangIUH/Project-FTA#134]
1/ Vào FTA tạo User mới.
=> Hiển thị thông báo lỗi.
Sửa lại thông báo lỗi. Đọc ko hiểu nổi lấy gì User bình thường hiểu.

Picture:
![bug013](https://cloud.githubusercontent.com/assets/5047540/18613043/6445e1ce-7d9a-11e6-8bf4-684c253981f8.png)

**Comment by lyquoclam** [comment]
Lam đã fixed roi nha
Note: Chưa được build

**Comment by baonh201092** [comment]
@lyquoclam . Ngày sinh nhập chữ và lưu vẫn được, chỉ có điều tạo xong user thì ngày sinh sẽ rỗng.

**Comment by lyquoclam** [comment]
Em đã fixed, nhưng đợi build của anh Dang ngày 22/9

**Comment by baonh201092** [comment]
Reviewed OK
