### ISSUE TITLE
[ADMIN SITE] Design dư trên giao diện

### ISSUE THREAD

**Issue by baonh201092** [LeDangIUH/Project-FTA#136]
Step:
1/ Đăng ký trên trang admin.
=> Giao diện design dư

Picture:
![bug016](https://cloud.githubusercontent.com/assets/5047540/18640653/3b047468-7ec3-11e6-9530-ac8ba8126257.PNG)

**Comment by baonh201092** [comment]
còn cái dưới nữa kìa @vdhung . Tàn dư của menu bên trái phải ko.

**Comment by lyquoclam** [comment]
Fixed, Đợi build cua anh Đăng ngay 23/9

**Comment by baonh201092** [comment]
Reviewed OK
