### ISSUE TITLE
[ADMIN SITE] Stress test button hiển thị thông tin sai

### ISSUE THREAD

**Issue by baonh201092** [LeDangIUH/Project-FTA#137]
Step:
1/ Đăng nhập bằng user admin - baonh02:zxcvbnm
2/ Click nhiều lần vào button Báo Cáo Sản Phẩm, Lịch trình nhóm sản phẩm.

**Comment by lyquoclam** [comment]
Note: Đợi build 3:00 AM (20/09/2016)

**Comment by baonh201092** [comment]
Reviewed OK
