### ISSUE TITLE
[ADMIN SITE] Ảnh chứng nhận không phóng to khi được user click vào

### ISSUE THREAD

**Issue by baonh201092** [LeDangIUH/Project-FTA#141]
Step:
1/ Đăng nhập User5: baonh0401:zxcvbnm
2/ Click vào hình ảnh chứng nhận sản phẩm
=> Không phóng to ảnh chứng nhận.

Picture:
![bug019](https://cloud.githubusercontent.com/assets/5047540/18677326/aa8ac278-7f82-11e6-947a-9dce2aae8b47.PNG)

**Comment by lyquoclam** [comment]
Lam fixed.

**Comment by baonh201092** [comment]
@lyquoclam . Ảnh chính trên trang chủ, logo công ty có cần phóng to không Lâm ơi.

**Comment by lyquoclam** [comment]
Hi Anh @baonh201092 
Không cần đâu anh Bảo, chỉ phóng to chứng thực thoi

**Comment by baonh201092** [comment]
Ok. Closed
