### ISSUE TITLE
[ADMIN SITE] Tràn nội dung cell table

### ISSUE THREAD

**Issue by baonh201092** [LeDangIUH/Project-FTA#145]
Step:
1/ Đăng nhập bằng spadmin:xxx
2/ Click hồ sơ Đăng ký

Picture:
![bug022](https://cloud.githubusercontent.com/assets/5047540/18680178/d54e8c88-7f8c-11e6-8bde-57afcc4024e0.PNG)
# Check luôn tất cả các table khác nữa.

**Comment by baonh201092** [comment]
@vdhung  . Bên nhóm sản phẩm vẫn còn Hưng à.
Nếu chuyển từ button sang text thì chuyển hết đi nha. Để đồng bộ.

**Comment by lyquoclam** [comment]
Hi Anh @baonh201092 
Em đã fixed roi, Đợi build của anh Đăng ngày 23/9

**Comment by baonh201092** [comment]
Reviewed OK
