### ISSUE TITLE
[ADMIN SITE] Cập nhật thông tin sản phẩm không thành công

### ISSUE THREAD

**Issue by baonh201092** [LeDangIUH/Project-FTA#147]
Step:
1/ Đăng nhập bằng baonh04:zxcvbnm
2/ Click edit thông tin sản phẩm.
3/ Add thêm thông tin mô tả
=> Không save được vì yêu cầu mã vạch phải thay đổi hoặc ko để trống.

Picture:
![bug024](https://cloud.githubusercontent.com/assets/5047540/18681035/6b2ac0a2-7f90-11e6-8c85-db4093e87aed.PNG)

**Comment by lyquoclam** [comment]
Fixed ticket này.

**Comment by baonh201092** [comment]
Giống #144

**Comment by lyquoclam** [comment]
Hi anh @baonh201092 
Test lai di anh
