### ISSUE TITLE
[ADMIN SITE] Không Duyệt được sản phẩm

### ISSUE THREAD

**Issue by nhanchuan** [LeDangIUH/Project-FTA#148]
1/ Lgoni spadmin
2/ Hồ Sơ Đăng Ký
3/ Click Xem sản phẩm chờ duyệt
![image](https://cloud.githubusercontent.com/assets/15918548/18683710/8c7abd88-7f9b-11e6-8f7c-2f20bd77d7ee.png)

4/ Nhập nội dung duyệt -> Duyệt

==> Lỗi

![image](https://cloud.githubusercontent.com/assets/15918548/18683689/75f03a16-7f9b-11e6-9ff1-f6cfc7ddcd31.png)

**Comment by lyquoclam** [comment]
Fixed

**Comment by baonh201092** [comment]
Reviewed OK
