### ISSUE TITLE
Cần bổ sung tính năng cho calendar

### ISSUE THREAD

**Issue by LeDangIUH** [LeDangIUH/Project-FTA#149]
![image](https://cloud.githubusercontent.com/assets/3908468/18794267/e1edff1a-81e8-11e6-8446-628fc23feac9.png)

Chỉ nhấp 2 nút <- và -> rất bất tiện là lâu cho người dùng

Chúy ý: cần ra sót toàn bộ các màn hình

**Comment by baonh201092** [comment]
cho thêm 2 nút nữa.
VD: <<  <  >  >>
<< thì cho next, prev năm,
< thì cho next, prev tháng.

**Comment by lyquoclam** [comment]
Em đã thay đổi 1 calendar loại khác. Đợi build ngày 25/9
