### ISSUE TITLE
[TASK] Chuyển màn hình sau khi Đăng Ký User

### ISSUE THREAD

**Issue by baonh201092** [LeDangIUH/Project-FTA#15]
1/ Access vào trang http://demo.thucphamminhbach.org/
2/ Click [Đăng Ký] -> Điền đầy đủ thông tin -> Click [Create an Account]
=> Hiển thị màn hình trắng

Picture:
![bug030](https://cloud.githubusercontent.com/assets/5047540/17864283/a27de230-68c7-11e6-992b-1eea5ca3e699.PNG)

**Comment by baonh201092** [comment]
Cái này có thể chuyển đến trang thông báo đã tạo thành công User Name.
Để lại trang Đăng Ký với thông tin User khi User, Email đã tồn tại mà thôi, đồng thời đưa ra thông báo cho User dưới field đó.

@nhanchuan check lại nha.

**Comment by nhanchuan** [comment]
1/ Access domain http://linhkien3h.com/page-reg-page
2/ Điền đầy đủ thông tin và thực hiện đăng ký.
==> Đăng ký thành công
3/ Check mail và click Active Link
==> Acctive thành công 

4/ Result:
![image](https://cloud.githubusercontent.com/assets/15918548/17953818/ca473dea-6aa0-11e6-83fb-f3b61540feb4.png)

![image](https://cloud.githubusercontent.com/assets/15918548/17953827/dd6739de-6aa0-11e6-92e3-f65f0c9e49e0.png)

**Comment by baonh201092** [comment]
Reviewed OK
