### ISSUE TITLE
[ADMIN SITE] Button chỉ hiển thị text => text

### ISSUE THREAD

**Issue by baonh201092** [LeDangIUH/Project-FTA#153]
Step:
1/ Đăng nhập bằng user spadmin:xxx, User 4, 3, 2.
View các table có sử dụng button chỉ hiện thị text: Địa chỉ, Mô Tả chung, tên User, Nhóm sản phẩm,

Check tại tất cả các button này không có sử dụng click thì chuyển sang text như phần tình trạng bài duyệt.

Picture:
![bug029](https://cloud.githubusercontent.com/assets/5047540/18807138/083d6ce2-826a-11e6-971b-bb96bc2a7c69.PNG)

**Comment by lyquoclam** [comment]
Hi Anh @baonh201092 
Ngay chỗ nhóm sản phẩm đó, Em nghĩ không cần sửa dau anh Bảo. Từ khi users ghê chuột vào mà nó hiển thị bàn tay thì người dùng sẽ nghĩ nó la button. Em nghĩ nen để như cũ nhóm sản phẩm, vay sẽ đẹp hơn

**Comment by baonh201092** [comment]
Nếu ko cần chỉnh nó thì để nó vậy cũng dc. Sửa những cái còn lại thôi

**Comment by lyquoclam** [comment]
Đợi build 0h 26/9
