### ISSUE TITLE
[ADMIN SITE] Kích thước cột và căn chỉnh

### ISSUE THREAD

**Issue by LeDangIUH** [LeDangIUH/Project-FTA#154]
màn hình supervise
![image](https://cloud.githubusercontent.com/assets/3908468/18807226/ed8ab0f6-826b-11e6-8285-0810b3bffe98.png)

@CẦN RÀ SÓT HẾT TẤT CA CÁC MÀN HÌNH

**Comment by LeDangIUH** [comment]
![image](https://cloud.githubusercontent.com/assets/3908468/18807263/c8b18b6e-826c-11e6-8ed8-c5689658b19f.png)

**Comment by lyquoclam** [comment]
Fixed user 4 va user5 
Note: Đợi build 0h 26/9
