### ISSUE TITLE
[ADMIN SITE] Lượt view sản phẩm

### ISSUE THREAD

**Issue by LeDangIUH** [LeDangIUH/Project-FTA#157]
Tôi đăng nhập 1 user trên tang home --> chọn vào 1 sản phẩm --> thấy tăng lên 1 

Cụng cùng 1 user đó tôi vào lịch sữ và nhấp lại sản phẩm ấy thì không tăng lượt view cho sản phẩm đó cũng như là danh mục sản phẩm yêu thích cũng ko tăng lên luôn

**Comment by baonh201092** [comment]
@lyquoclam . Anh click vào sản phẩm cũng không thấy tăng view Lâm à

**Comment by baonh201092** [comment]
@lyquoclam Cái này có thể bị vấn đề sync gì không, lúc đầu anh click rất nhiều nhưng nó ko lên view, giờ thì lên cái đùng một đống.

**Comment by lyquoclam** [comment]
Anh @vdhung 

Anh làm defect này nha, máy anh Dang ko co SQL em check ko dc. 
Dang nhập user4  vào trang này "http://localhost:1215/Dashboard/Bussiness" , sẵn check chỗ lượt tra cứu sản phẩm hiện lượt view ko chính xác

**Comment by lyquoclam** [comment]
Anh Hung đã fixed
