### ISSUE TITLE
[ADMIN SITE] Notification

### ISSUE THREAD

**Issue by LeDangIUH** [LeDangIUH/Project-FTA#158]
Người dùng warning san phẩm ==> **admin không nhận được notification ??**

Admin chuyển cho doanh nghiệp thì doanh nghiệp nhận được notifivation đúng rồi sao chình 1 người dùng đó lại nhận được notification y chan doanh nghiệp đó

**Comment by vdhung** [comment]
Người dùng warning san phẩm ==> admin không nhận được notification ??
===> Admin quản lý nhóm sản phẩm đó mới nhận dc thông báo sản phẩm từ nhóm đó

Admin chuyển cho doanh nghiệp thì doanh nghiệp nhận được notifivation đúng rồi sao chình 1 người dùng đó lại nhận được notification y chan doanh nghiệp đó
==> fixed: ko notification đến người cảnh báo...
