### ISSUE TITLE
[ADMIN SITE] Hint là không quá 250 kí tự, message hiện 200

### ISSUE THREAD

**Issue by baonh201092** [LeDangIUH/Project-FTA#159]
Step:
1/ Đăng nhập bằng user5
2/ Click report
3/ Click Cảnh Báo
=> Chỉnh hint về 200
Picture:
![bug030](https://cloud.githubusercontent.com/assets/5047540/18809155/507d6806-829f-11e6-9a8a-df2c8c665c61.PNG)

**Comment by baonh201092** [comment]
@lyquoclam . Hiển thị đồng bộ hint cho các textbox Bình luận khác nữa nha Lâm, a thấy cái có cái ko đấy. Như trong trang sản phẩm thì phần Bình Luận ko có giống.

**Comment by lyquoclam** [comment]
Đợi build 0h 26/9
