### ISSUE TITLE
[ADMIN SITE] Hiển thị số lượt comment chưa chính xác

### ISSUE THREAD

**Issue by baonh201092** [LeDangIUH/Project-FTA#163]
Step:
1/ Đăng nhập bằng User5
2/ Bình luận 1 sản phẩm, trả lời bình luận
=> Count hiện tại là 1, nên tính luôn các bình luận con.

Sửa sau, chờ @LeDangIUH confirm.

**Comment by LeDangIUH** [comment]
ko can
