### ISSUE TITLE
[ADMIN SITE] Cho hỉnh ảnh vào center để cân bằng

### ISSUE THREAD

**Issue by baonh201092** [LeDangIUH/Project-FTA#164]
Step:
1/ Đăng nhập User5.
2/ Click Tên công trong 1 sản phẩm
=> View thấy logo Công ty lệch trái

Picture:
![bug034](https://cloud.githubusercontent.com/assets/5047540/18809632/3ae12c1a-82ab-11e6-9c6d-0a3024b1a33d.png)

**Comment by baonh201092** [comment]
Nếu thêm viền ảnh thấy OK hơn thì thêm nha @lyquoclam.

**Comment by lyquoclam** [comment]
Hình ảnh đã trung tâm. Đợi build 0h 26/9
