### ISSUE TITLE
[ADMIN SITE] Hightlight Tên Công Ty

### ISSUE THREAD

**Issue by baonh201092** [LeDangIUH/Project-FTA#166]
Picture: chữ thông tin công ty còn to hơn tên công ty, nhìn hơi kì. Nên hightlight Tên Công Ty lên cho tương xứng.
![bug036](https://cloud.githubusercontent.com/assets/5047540/18809699/7185288c-82ad-11e6-9fd4-aaa73a367627.PNG)

**Comment by lyquoclam** [comment]
Hi Anh @baonh201092 
Removed tên công ty, bởi vì trong input có tên công ty roi không cần hiện tên công ty trên header nữa

**Comment by LeDangIUH** [comment]
![image](https://cloud.githubusercontent.com/assets/3908468/19016097/15287538-883b-11e6-973f-0d3d875edea4.png)

Vẫn còn ten cong ty

**Comment by lyquoclam** [comment]
Fixed (1/10/2016)
Node: đợi build
