### ISSUE TITLE
[ADMIN SITE] Hiển thị Cảnh báo sản phẩm ở trang chủ, nhưng không hiển thị trong trang chi tiết sản phẩm

### ISSUE THREAD

**Issue by baonh201092** [LeDangIUH/Project-FTA#168]
Picture 1: Hiển thị trên trang chủ
![bug038_1](https://cloud.githubusercontent.com/assets/5047540/18810083/3358d41e-82b7-11e6-9aee-5efb8b517e71.PNG)

Picture 2: Hiển thị chi tiết sản phẩm
![bug038_2](https://cloud.githubusercontent.com/assets/5047540/18810085/4248b75a-82b7-11e6-92c4-3da9dda42fb4.PNG)

**Comment by lyquoclam** [comment]
Fixed, Đợi build 0h 26/9
