### ISSUE TITLE
[BUG] Mất tiêu đề bài viết khi chuyển từ Việt -> Anh

### ISSUE THREAD

**Issue by baonh201092** [LeDangIUH/Project-FTA#17]
1/ Access vào trang http://demo.thucphamminhbach.org/
2/ Click tiếng Việt -> [Tin Tức & Sự Kiện] -> [Tin Tức] -> `Click tiếng Anh hoặc
[Xuất khẩu thủy sản có thể đạt mốc trên 7 tỷ USD] -> Click tiếng Anh
=> Mất tiêu đề hiển thị

Picture 1:
![bug031_1](https://cloud.githubusercontent.com/assets/5047540/17865531/282294da-68cd-11e6-83b8-0a4108bedd58.PNG)

Picture 2:
![bug031_2](https://cloud.githubusercontent.com/assets/5047540/17865532/2b11083e-68cd-11e6-9208-aead9f69589f.PNG)

Picture 3:
![bug031_3](https://cloud.githubusercontent.com/assets/5047540/17865579/5a0e3238-68cd-11e6-8ad6-2b50eb4a4273.PNG)

**Comment by nhanchuan** [comment]
cái này do Người viết Bài Quên không viết Tiêu Đề Cho Bài.

![1](https://cloud.githubusercontent.com/assets/15918548/17877616/c1f62388-690e-11e6-9bf8-04fa80d6f9ab.PNG)

**Comment by nhanchuan** [comment]
Tui sẽ cho yêu cầu bắt buột người dùng nhập

**Comment by baonh201092** [comment]
Reviewed OK
