### ISSUE TITLE
[ADMIN SITE] mất menu bên trái đối với admin

### ISSUE THREAD

**Issue by LeDangIUH** [LeDangIUH/Project-FTA#170]
Khi super admin tạo mới 1 admin sao đó dùng admin mới login thì mất 

![image](https://cloud.githubusercontent.com/assets/3908468/18810379/c55b916a-82be-11e6-819b-97cb69e691f7.png)

**Comment by lyquoclam** [comment]
Hi Anh @LeDangIUH 

Đóng ticket nay di anh, hom qua em và anh bàn ve vụ set quyền Tài Khoản Quảng Tri roi do
