### ISSUE TITLE
[ADMIN SITE] tên lable sai

### ISSUE THREAD

**Issue by LeDangIUH** [LeDangIUH/Project-FTA#172]
![image](https://cloud.githubusercontent.com/assets/3908468/18810434/f5a72b44-82bf-11e6-8ca8-7bbd199cbec5.png)

admin --> Thêm nhóm --> 'Chỉnh sửa thông tin nhóm sản phẩm' ==> **Sai**

Edit lại "Thêm nhóm sản phẩm"

**Comment by lyquoclam** [comment]
Fixed, đợi build 3h 26/9
