### ISSUE TITLE
[ADMIN SITE] lable sai

### ISSUE THREAD

**Issue by LeDangIUH** [LeDangIUH/Project-FTA#173]
Chọn dấu cộng

![image](https://cloud.githubusercontent.com/assets/3908468/18810438/40cf2996-82c0-11e6-9e1e-97e2f4052228.png)

![image](https://cloud.githubusercontent.com/assets/3908468/18810439/7181cc56-82c0-11e6-9246-ded4f82f587d.png)

"Nhóm sản phẩm" ==> "Lựa chọn người quản trị"
"Nhóm" ==> "Tài khoản quản trị"

**Comment by lyquoclam** [comment]
Fixed, đợi build 3h 26/9
