### ISSUE TITLE
[ADMIN SITE] hình đại diện chứng nhận

### ISSUE THREAD

**Issue by LeDangIUH** [LeDangIUH/Project-FTA#175]
![image](https://cloud.githubusercontent.com/assets/3908468/18810548/854f3fd6-82c3-11e6-85d9-94733540b6d7.png)

![image](https://cloud.githubusercontent.com/assets/3908468/18810576/f967ada4-82c3-11e6-9be5-5f8a48ec5f97.png)

**Comment by lyquoclam** [comment]
Fixed, đợi build 27/9
