### ISSUE TITLE
[ADMIN SITE] performance cho gui hồ so

### ISSUE THREAD

**Issue by LeDangIUH** [LeDangIUH/Project-FTA#176]
![image](https://cloud.githubusercontent.com/assets/3908468/18810612/23a945b8-82c5-11e6-9df3-da3b6f7a02f9.png)

Cần thêm một su kien de cho người ta biết là hồ sơ đang được gửi đi "Đăng gửi hồ sơ ...."

**Comment by lyquoclam** [comment]
Em đã them a hộp thoại dang đợi. Đợi build 27/9
