### ISSUE TITLE
[WEB] Mặc định khi nhấp "Cộng đồng FTA"

### ISSUE THREAD

**Issue by LeDangIUH** [LeDangIUH/Project-FTA#178]
Khi trang loading lên chư đăng nhập gì cả người dùng nhấp vào button "Cộng đồng FTA" thì hiện thị ra trang login website như bên dưới

![image](https://cloud.githubusercontent.com/assets/3908468/18862439/5aa3cfdc-84b6-11e6-8223-5c2f3547c726.png)

Không hiện ra đang login của admin

![image](https://cloud.githubusercontent.com/assets/3908468/18862452/70f907c0-84b6-11e6-80a0-9e0935083cb7.png)

**Comment by nhanchuan** [comment]
- Chờ bản Update sau 6h : 27/09/2016
