### ISSUE TITLE
[BUG][URGEN] Performance load page chậm

### ISSUE THREAD

**Issue by baonh201092** [LeDangIUH/Project-FTA#18]
1/ Access vào trang http://demo.thucphamminhbach.org/
=> Hiển thị trang chậm hơn.

Picture:
![bug028](https://cloud.githubusercontent.com/assets/5047540/17865931/ce526078-68ce-11e6-92a1-58926ec1203b.PNG)

**Comment by nhanchuan** [comment]
1/ Access vào trang http://linhkien3h.com/
=> Đã nén ảnh :  Hiển thị trang nhanh hơn.

**Comment by baonh201092** [comment]
Reviewed OK
