### ISSUE TITLE
[BUG] Select Box vượt size ra ngoài group

### ISSUE THREAD

**Issue by baonh201092** [LeDangIUH/Project-FTA#19]
1/ Login trang Admin (User = admin, pass = zxcvbnm)
2/ Click [Bài Viết] -> Click [Viết Bài Mới] -> Title [Đăng] chọn [Chỉnh Sửa]
=> Select Box hiển thị vượt ra ngoài group.

Picture:
![screen shot 2016-08-24 at 22 25 45](https://cloud.githubusercontent.com/assets/5047540/17936949/b494cfc2-6a4a-11e6-9754-92806b7e5c8d.png)

**Comment by nhanchuan** [comment]
đã fix Size 
![image](https://cloud.githubusercontent.com/assets/15918548/17939187/94a1f4b6-6a53-11e6-90e2-503d971b9bf8.png)

**Comment by baonh201092** [comment]
Review OK
