### ISSUE TITLE
[ADMIN SITE] Dien thoai 

### ISSUE THREAD

**Issue by LeDangIUH** [LeDangIUH/Project-FTA#190]
[9:32:58 PM] Le Dang: (84.8) 38294440
[9:33:48 PM] Le Dang: +084
[9:33:59 PM] Le Dang: (08) 8 350 562

Fax cung tương tu

**Comment by lyquoclam** [comment]
Fixed date(1/10/2016)
Note: đợi build

Anh @LeDangIUH 
nhớ chạy script bên dưới cho tất cả database nha:

```
ALTER TABLE RequestCompany
ALTER COLUMN FaxNumber nvarchar(30)
GO
ALTER TABLE RequestCompany
ALTER COLUMN TaxNumber nvarchar(30)
GO
ALTER TABLE RequestCompany
ALTER COLUMN PhoneNumber nvarchar(30)
```
