### ISSUE TITLE
[ADMIN SITE] điều chình giao diện

### ISSUE THREAD

**Issue by LeDangIUH** [LeDangIUH/Project-FTA#193]
![image](https://cloud.githubusercontent.com/assets/3908468/19014783/2e1954b0-8820-11e6-83ff-bd490591fd15.png)

![image](https://cloud.githubusercontent.com/assets/3908468/19014789/725f3400-8820-11e6-8a04-81c0f5683306.png)

**Comment by lyquoclam** [comment]
Fixed (2/10/2016)
Note: Đợi build
