### ISSUE TITLE
[ADMIN SITE] Lịch sử bị trùng

### ISSUE THREAD

**Issue by LeDangIUH** [LeDangIUH/Project-FTA#196]
làm theo từng bước sau:
1. Home
2. nhấp vào "Mực nướng cán duỗi"
3. Nhấp "Lịch sử tra cứu"

Làm nhiều lần như vậy kết quả bị như sau:

![image](https://cloud.githubusercontent.com/assets/3908468/19016237/8c0bfcf8-883e-11e6-9a5d-bb8a625cf99a.png)

**Comment by lyquoclam** [comment]
Fixed (2/10/2016)
Node: Đợi build
