### ISSUE TITLE
[ADMIN SITE] Xóa 1 sãn phâm trong lich sừ

### ISSUE THREAD

**Issue by LeDangIUH** [LeDangIUH/Project-FTA#197]
Vào "lịch sử tra cứu"

Nhấp lần 1 biểu tượng "X" Báo đã xóa 1 nhưng sản phẩm vẫn còn nhấp thêm mấy lần nữa mới thấy mất.

**Comment by lyquoclam** [comment]
Fixed (2/10/2016)
Note: đợi build
