### ISSUE TITLE
[ADMIN SITE] Logo bi vo

### ISSUE THREAD

**Issue by LeDangIUH** [LeDangIUH/Project-FTA#199]
trên chrome
![image](https://cloud.githubusercontent.com/assets/3908468/19016295/efbfa3b6-883f-11e6-93c0-35741ebfddec.png)

Trên FF
![image](https://cloud.githubusercontent.com/assets/3908468/19016298/fd08bf62-883f-11e6-81a8-ee8448701155.png)

**Comment by lyquoclam** [comment]
Fixed (2/10/2016)
Note: đợi build

**Comment by LeDangIUH** [comment]
test lai trên firefox @lyquoclam

**Comment by lyquoclam** [comment]
Fixed 13/10/2016
