### ISSUE TITLE
[TASK] Xóa nếu các button dưới không cần.

### ISSUE THREAD

**Issue by baonh201092** [LeDangIUH/Project-FTA#20]
1/ Login trang Admin (User = admin, pass = zxcvbnm)
2/ Click [Pictures] -> Thư Viện
=> Nếu các button này không cần thiết thì nên xóa đi.
- button thu / giãn: OK
- button config: có cần phải config gì ko, nếu ko thì bỏ.
- button reload: đã phân trang rồi nên không cần reload nữa.
- button delete: chỉ có 1 thư viện thôi nên delete sẽ mất hiển thị của User => bỏ.

Picture:
![bug033](https://cloud.githubusercontent.com/assets/5047540/17939397/aa48ef1c-6a54-11e6-8332-3868561d12b5.PNG)

**Comment by nhanchuan** [comment]
- Đã fix button
- Chỉ để button collapse cho content

**Comment by baonh201092** [comment]
Reviewed OK
