### ISSUE TITLE
[ADMIN SITE] Danh sanh nguoi dung lỗi

### ISSUE THREAD

**Issue by LeDangIUH** [LeDangIUH/Project-FTA#200]
Khi spadmin hay admin nhấp vào "Danh sách người dùng" ==> Lỗi

![image](https://cloud.githubusercontent.com/assets/3908468/19016330/9bcaef3a-8840-11e6-8b72-78ca9a897862.png)

**Comment by lyquoclam** [comment]
Fixed date(1/10/2016)
Note: đợi build
