### ISSUE TITLE
[ADMIN SITE] Binh luận avartar

### ISSUE THREAD

**Issue by LeDangIUH** [LeDangIUH/Project-FTA#203]
![image](https://cloud.githubusercontent.com/assets/3908468/19016472/178cf736-8845-11e6-9019-24dae3af371f.png)

không lấy duoc avartar cua nguoi binh luan

**Comment by LeDangIUH** [comment]
Ai không có avertar thì hiện avartar mặc định

Hiện tại, 
![image](https://cloud.githubusercontent.com/assets/3908468/19037208/411cc0e4-899f-11e6-96c1-4397991bd4a3.png)

**Comment by vdhung** [comment]
cai nay t up localhost mak ?? co up tren hosst dau , mak image default ???????
