### ISSUE TITLE
[ADMIN SITE] Edit tên label

### ISSUE THREAD

**Issue by LeDangIUH** [LeDangIUH/Project-FTA#204]
![image](https://cloud.githubusercontent.com/assets/3908468/19037325/d57c1672-899f-11e6-9131-c8f84d2b3fe7.png)

"Taxnumber" ==> Mã số thuế
"Faxnumber" ==> Fax

**Comment by lyquoclam** [comment]
Fixed 03/10/2016
Note: Đợi build
