### ISSUE TITLE
[ADMIN SITE] Điểu chỉnh giao diên

### ISSUE THREAD

**Issue by LeDangIUH** [LeDangIUH/Project-FTA#208]
Phần user 5 và 4 cần điều chỉnh lại giao diện cho linh hoạt và reponsive
{Liên tuc cap nhận }
1. Home
   ![image](https://cloud.githubusercontent.com/assets/3908468/19121597/4decb226-8b51-11e6-880c-a85e76912b34.png)

**Comment by lyquoclam** [comment]
Fixed 06/10/2016
Note: Đợi build
