### ISSUE TITLE
[WEB] [Q&A] Block hiển thị Chuyên Mục

### ISSUE THREAD

**Issue by baonh201092** [LeDangIUH/Project-FTA#21]
1/ Block 1 dùng để làm gì có cần thiết hay không, dùng để làm gì khi đã có block thông tin kế bên.
2/ Block 2 nên hiện ra khi 1 item chuyên mục được select để có thể chỉnh sửa hoặc thêm.

Picture:
![bug001](https://cloud.githubusercontent.com/assets/5047540/17940211/47ea7e40-6a58-11e6-8f67-b8a5b19fae19.PNG)

**Comment by nhanchuan** [comment]
1/.Block 1 chức năng chỉnh sữa nhanh menu.
2. Block 2 chức năng add các subitem vào Mainmenu

**Comment by baonh201092** [comment]
Reviewed OK
