### ISSUE TITLE
[WEB] [Q&A]  Sau khi đăng bài mới mà không chọn chuyên mục.

### ISSUE THREAD

**Issue by baonh201092** [LeDangIUH/Project-FTA#22]
1/ Sau khi đăng bài mới mà không chọn chuyên mục.
Sau đó duyệt thì bài đăng sẽ được hiển thị ở đâu.
==> Nên bắt buộc người dùng chọn chuyên mục.

**Comment by baonh201092** [comment]
2/ Sau khi Đăng bài mới thì nên chuyển sang trang Tất Cả Bài Viết thay vì cho thay đổi bài viết.

**Comment by nhanchuan** [comment]
Đăng bài mới  => chuyển qua Update giống với nhiều hệ CMS khác
VD như WP
