### ISSUE TITLE
[WEB] [BUG] Chuyển tất cả nội dung trang Admin về tiếng Việt (nếu có thể)

### ISSUE THREAD

**Issue by baonh201092** [LeDangIUH/Project-FTA#23]
1/ Login trang Admin (User = admin, pass = zxcvbnm)
=> chuyển sang tất cả nội dung trang sang tiếng Việt.

Picture:
![bug001](https://cloud.githubusercontent.com/assets/5047540/17992668/b1ff41fa-6b73-11e6-98d1-cd3c5573a573.PNG)

**Comment by baonh201092** [comment]
- Submit => Cập Nhật
- Select => Chọn
- DB_ID: không cần thiết phải show ID trong DB cho admin, còn nếu show thì phải add dữ liệu chính xác, không để tình trạng 5 6 rồi 9, nhưng tốt nhất nên cho theo số thứ tự tăng dần không thay đổi. Menu nào thay đổi vị trí thì thay đổi số thứ tự thôi.
- Sub Mennu Settings => Cài Đặt Menu Con
  Picture: ![bug021](https://cloud.githubusercontent.com/assets/5047540/18097834/c19d702a-6f09-11e6-85bb-b66853beb3bf.PNG)

**Comment by baonh201092** [comment]
- Administrator => Quản Lý
- FORUM => Diễn Đàn
- MORE => Mở Rộng
- Photo Gallery => Danh Mục Hình
- Library => Bộ Sưu Tập
- Category => Chuyên Mục
- Select Category => Chọn Chuyên Mục
- Image Title (VN - EN) => Tiêu Đề Ảnh (VN - EN)
- Short Description (VN - EN) => Mô Tả Sơ Lược (VN - EN)
- Upload File => Tải Tập Tin
- You can upload JPG, GIF, or PNG file. Maximum file size is 4MB. => Bạn chỉ có thể tải lên các tập tin ảnh JPG hoặc GIF hoặc PNG. Dung lượng tối đa là 4MB.
- Choose File => Chọn Tập Tin
- No file chosen => Không Có Tập Tin Được Chọn (Sửa cả thông báo)
- Add New => Thêm Mới
- Edit Image Infor => Chỉnh Sửa Thông Tin Hình Ảnh
- Title => Tiêu Đề
- Descriptions =>  Mô Tả
- Select => Chọn
- Last => Trang Cuối
  Picture:![bug022](https://cloud.githubusercontent.com/assets/5047540/18098123/000fbfa6-6f0b-11e6-9fd0-661df3eb0a49.PNG)

## @nhanchuan  Lưu ý viết theo format viết hoa các chữ đầu, tránh để tình trạng thế này

VD: Tiêu đề bài viết => Tiêu Đề Bài Viết.

**Comment by baonh201092** [comment]
- Term Of Service => Điều Khoản Dịch Vụ
- Setting => Cài Đặt
- Privacy Policy => Điều Khoản Dịch Vụ
- Content VN (EN) => Nội Dung VN (EN)
- Save Policy => Lưu
  Picture:
  ![bug023](https://cloud.githubusercontent.com/assets/5047540/18098736/a2b850d6-6f0d-11e6-9548-9a0ac187857a.PNG)

**Comment by baonh201092** [comment]
Picture: Như trên nhưng xem lại phần Thẻ Privacy Policy có trùng nhau hay không.
![bug024](https://cloud.githubusercontent.com/assets/5047540/18098853/3a8101f6-6f0e-11e6-88f5-a9bd57e38937.PNG)

**Comment by baonh201092** [comment]
Picture: Như trên
![bug025](https://cloud.githubusercontent.com/assets/5047540/18098968/af052fac-6f0e-11e6-9058-7368e83c47cc.PNG)

**Comment by baonh201092** [comment]
Picture: Như trên, tiêu đề sai
![bug026](https://cloud.githubusercontent.com/assets/5047540/18099035/f0f00284-6f0e-11e6-95d4-eab3b2223936.PNG)

**Comment by baonh201092** [comment]
- Setting SubSlider => Cài Đặt SubSlider
- Edit SubSlider => Chỉnh Sửa SubSlider
- From Library => Từ Thư Viện
  Picture:
  ![bug027](https://cloud.githubusercontent.com/assets/5047540/18099328/28844736-6f10-11e6-9f16-5ae7c6bc61c7.PNG)

**Comment by baonh201092** [comment]
Picture:
![bug028](https://cloud.githubusercontent.com/assets/5047540/18099469/dd6fdd0e-6f10-11e6-9551-eed19eea8664.PNG)

**Comment by baonh201092** [comment]
- All User => Tất Cả Người Dùng (Quản Trị)
- Users Admin => Tất Cả Người Dùng (Quản Trị)
- Thêm thông tin trường để hiểu bảng.
  Picture:
  ![bug029](https://cloud.githubusercontent.com/assets/5047540/18099509/0b97e3ca-6f11-11e6-9df5-ceda11c23df8.PNG)

**Comment by baonh201092** [comment]
Picture: 
![bug030](https://cloud.githubusercontent.com/assets/5047540/18099587/6f026cbe-6f11-11e6-841e-eaa56dcdd65a.PNG)

**Comment by baonh201092** [comment]
- Thư Viện Hình Ảnh Images Manager => bỏ phần sau thừa.
- Upload By => Tải Lên Bởi
- Remove các hình ảnh lỗi
  Picture: 
  ![bug001](https://cloud.githubusercontent.com/assets/5047540/18115652/4688d57a-6f6b-11e6-98a8-e8f56fba2c70.PNG)

**Comment by baonh201092** [comment]
- BgCLass => cho người dùng chọn từ bảng màu.
  Picture:
  ![bug002](https://cloud.githubusercontent.com/assets/5047540/18115980/166b5004-6f6e-11e6-86df-f03b9b655c23.PNG)

**Comment by baonh201092** [comment]
- Thêm tên trường để mô tả thông tin của Bảng.
  Picture:
  ![bug0023](https://cloud.githubusercontent.com/assets/5047540/18119179/97f3c308-6f83-11e6-93d4-ed561b398dc5.PNG)

**Comment by baonh201092** [comment]
Picture:
![bug003](https://cloud.githubusercontent.com/assets/5047540/18119694/0dfdb2c8-6f86-11e6-9fc3-b0e32a18b52e.PNG)

**Comment by baonh201092** [comment]
Picture:
![bug004](https://cloud.githubusercontent.com/assets/5047540/18119533/5da054c6-6f85-11e6-9ecb-811dca25b61d.PNG)

**Comment by baonh201092** [comment]
Picture:
![bug031](https://cloud.githubusercontent.com/assets/5047540/18134304/169a6268-6fc8-11e6-96a7-02e4066daf5a.PNG)

**Comment by baonh201092** [comment]
Picture:
![bug032](https://cloud.githubusercontent.com/assets/5047540/18134313/23a90eb4-6fc8-11e6-9a8b-d23d68343f69.PNG)

**Comment by baonh201092** [comment]
Picture:
![bug036](https://cloud.githubusercontent.com/assets/5047540/18138324/60e65648-6fd6-11e6-8241-b6c1ee996a31.PNG)

**Comment by nhanchuan** [comment]
- Đã fix

**Comment by baonh201092** [comment]
Reviewed OK
