### ISSUE TITLE
[ADMIN] Khi giám sát chéo không thấy thông tin

### ISSUE THREAD

**Issue by LeDangIUH** [LeDangIUH/Project-FTA#233]
Cong ty giám sát chéo nhưng khi admin nhấp vào xem báo cáo thì không dử liệu

![image](https://cloud.githubusercontent.com/assets/3908468/19855416/078efdb0-9fa7-11e6-9a12-0c3667a29e9c.png)

**Comment by lyquoclam** [comment]
Fixed 31/10/2016
Note: Đợi build
