### ISSUE TITLE
[ADMIN] Hinh logo cong ty

### ISSUE THREAD

**Issue by LeDangIUH** [LeDangIUH/Project-FTA#234]
![image](https://cloud.githubusercontent.com/assets/3908468/19855512/96612784-9fa7-11e6-8c40-b53741a86d0a.png)

Admin ==> Danh sách danh nghiệp ==> Khong hiện logo

**Comment by lyquoclam** [comment]
Hi anh @LeDangIUH 

Như đã thảo luận trên skype. Các logo trên cột "Các tài khoản" là logo của các tài khoản mà công ty đó quản ly. Note: Không phải là logo của công ty
