### ISSUE TITLE
[WEB] [BUG］Xóa button không sử dụng

### ISSUE THREAD

**Issue by baonh201092** [LeDangIUH/Project-FTA#24]
1/ Login trang Admin (User = admin, pass = zxcvbnm)
2/ Click [Bài Viết] -> [Tất cả bài viết]
=> Xóa button không sử dụng

Picture:
![bug005](https://cloud.githubusercontent.com/assets/5047540/18012300/2ca3dd20-6be3-11e6-8c10-a85227a2aad2.PNG)

**Comment by baonh201092** [comment]
@nhanchuan trang này đã phân trang rồi thì dùng button này làm gì nữa chuẩn ơi.

**Comment by nhanchuan** [comment]
- Đã fix

**Comment by baonh201092** [comment]
Reviewed OK
