### ISSUE TITLE
[WEB] [BUG] Không tick checkbox [Duyệt] nhưng vẫn hiển thị bài Đăng.

### ISSUE THREAD

**Issue by baonh201092** [LeDangIUH/Project-FTA#26]
1/ Login trang Admin (User = admin, pass = zxcvbnm)
2/ Đăng bài viết mới (Chọn Đăng Bài) -> Click [Tất Cả Bài Viết] -> Tìm bài viết vừa Đăng.
=> Bài viết vừa Đăng nhưng checkbox [Duyệt] không được tick.

Picture 1:
![bug007](https://cloud.githubusercontent.com/assets/5047540/18026378/e715cbba-6c6e-11e6-9c5f-5b435104957e.PNG)

Picture 2:
![bug008](https://cloud.githubusercontent.com/assets/5047540/18026379/eb4cb1e4-6c6e-11e6-9145-53b150b5eaf9.PNG)

**Comment by baonh201092** [comment]
Check thêm các case khác cho chắc chắn phần duyệt bài.

**Comment by baonh201092** [comment]
Trạng thái là [Đăng Bài] nhưng checkbox duyệt vẫn chưa được tick. Check case này thật kỹ @nhanchuan  ơi.
Picture 1:
![bug043_1](https://cloud.githubusercontent.com/assets/5047540/18225566/a3d33a02-721f-11e6-8cdb-4a5f8a131795.PNG)

Picture 2:
![bug043_2](https://cloud.githubusercontent.com/assets/5047540/18225567/a6f525b0-721f-11e6-92de-57d2c3573f5e.PNG)

**Comment by nhanchuan** [comment]
- Có sai xót trong hiện trạng thái "Duyệt",.
  => Đã fix

**Comment by baonh201092** [comment]
Check lại @nhanchuan ơi, Click bỏ [Duyệt] thì bài Đăng vẫn còn.

**Comment by baonh201092** [comment]
Reviewed OK
