### ISSUE TITLE
[WEB] [BUG] Tìm kiếm không chính xác

### ISSUE THREAD

**Issue by baonh201092** [LeDangIUH/Project-FTA#28]
Picture 1:
![bug013](https://cloud.githubusercontent.com/assets/5047540/18033356/549e2f96-6d4c-11e6-82e6-645d3cd585c5.PNG)

Picture 2:
![bug013_1](https://cloud.githubusercontent.com/assets/5047540/18033360/5ae3bc04-6d4c-11e6-8ff6-71e5d24bfc40.PNG)

**Comment by baonh201092** [comment]
@nhanchuan Check luôn các box tìm kiếm khác.

**Comment by nhanchuan** [comment]
- Cái này phải nhờ đồng chí Đăng Run cái Full text trong sql-server
  ![image](https://cloud.githubusercontent.com/assets/15918548/18033838/a24a552a-6d57-11e6-944b-4aef6bb501d8.png)
