### ISSUE TITLE
[BUG] Ảnh lỗi trong thư viện

### ISSUE THREAD

**Issue by baonh201092** [LeDangIUH/Project-FTA#29]
Picture:
![bug015](https://cloud.githubusercontent.com/assets/5047540/18033465/de2f552a-6d4f-11e6-9763-8716186a0856.PNG)

**Comment by nhanchuan** [comment]
- Do sử dụng chung DB, mà source upload lên host khác nên không có Images trong folder
- Ảnh nào trong thư viện lỗi thì xóa là nó xóa lun Link trong DB

**Comment by nhanchuan** [comment]
- Đã xóa hết ảnh bị mất

**Comment by baonh201092** [comment]
Reviewed OK
