### ISSUE TITLE
[BUG] Không đăng được bài mới

### ISSUE THREAD

**Issue by baonh201092** [LeDangIUH/Project-FTA#3]
1/ Login trang Admin    (User = admin, pass = zxcvbnm)
2/ Click [Bài Viết] -> click [Viết Bài Mới]  
3/ Ở Title [Trạng Thái] -> click [chỉnh sửa] -> chọn [Đăng Bài] -> click OK -> Click Cập Nhật Bài Viết
==> Không chuyển sang trạng thái Đăng Bài được.
![image](https://cloud.githubusercontent.com/assets/5047540/17835795/972126d0-67a6-11e6-9446-7e1fd8440b9a.png)

**Comment by baonh201092** [comment]
Reviewed OK.

**Comment by baonh201092** [comment]
Không thể đăng bài được.
![screen shot 2016-08-24 at 22 13 42](https://cloud.githubusercontent.com/assets/5047540/17936423/f5d522e0-6a48-11e6-9f9f-a558d57b50f6.png)

**Comment by nhanchuan** [comment]
1/ Access http://linhkien3h.com/Admin/Pages/Post-New.aspx
username: admin
pass: zxcvbnm
2/ Đăng bài với nội dung như trong hình.
![image](https://cloud.githubusercontent.com/assets/15918548/17951148/253e7fb8-6a8a-11e6-8db2-0b381d02e96a.png)

![image](https://cloud.githubusercontent.com/assets/15918548/17951160/439d624e-6a8a-11e6-9675-6c15258bd8c5.png)

3/ Chọn Chuyên mục [Tin tức] ->Chọn trạng thá i"--Đăng bài--" -> click [Đăng bài viết]
4/ Kết quả => Đăng bài thành công => chuyển qua trang Update
![image](https://cloud.githubusercontent.com/assets/15918548/17951238/cb1fd292-6a8a-11e6-8846-bbde20145113.png)

5/ Kết quả xem trên website
![image](https://cloud.githubusercontent.com/assets/15918548/17951258/ffe7d272-6a8a-11e6-966c-26ae27f175de.png)

**Comment by baonh201092** [comment]
Reviewed OK
