### ISSUE TITLE
[BUG] Không có button xóa [Chuyên Mục Thư Viện Hình Ảnh]

### ISSUE THREAD

**Issue by baonh201092** [LeDangIUH/Project-FTA#31]
Picture: Cần button xóa chuyên mục đã tạo
![bug019](https://cloud.githubusercontent.com/assets/5047540/18093371/cec5e38c-6ef9-11e6-9261-67667f0abbb9.PNG)

**Comment by baonh201092** [comment]
@nhanchuan Suy nghĩ cách xử lí khi trong chuyên mục đó có hình ảnh.

**Comment by nhanchuan** [comment]
- Đã Fix

**Comment by baonh201092** [comment]
@nhanchuan  Xét thêm case là có ảnh trong chuyên mục đó nữa Chuẩn à, nếu xóa chuyên mục thì sẽ thông báo User tồn tại ảnh và muốn xóa hay không. Ok thì xóa hết ảnh liên quan trong chuyên mục luôn.

**Comment by baonh201092** [comment]
Xóa luôn cũng được
