### ISSUE TITLE
[BUG] Hiển thị button bị lệch

### ISSUE THREAD

**Issue by baonh201092** [LeDangIUH/Project-FTA#33]
Picture:
![bug008](https://cloud.githubusercontent.com/assets/5047540/18120358/53d6dc18-6f89-11e6-9c27-a2eb0e31db6b.PNG)

**Comment by nhanchuan** [comment]
- nó là control asp, cho hiển thị về mặc định thì không bị lệch nữa.
  ![image](https://cloud.githubusercontent.com/assets/15918548/18136946/b9b8f4ca-6fd0-11e6-9b5c-cd1a59530a81.png)

**Comment by baonh201092** [comment]
Reviewed OK
