### ISSUE TITLE
[BUG] Focus còn được lưu giữ khi xóa 1 line

### ISSUE THREAD

**Issue by baonh201092** [LeDangIUH/Project-FTA#34]
Picture 1: Xóa 1 line
![bug009_1](https://cloud.githubusercontent.com/assets/5047540/18120938/5d4596ba-6f8c-11e6-9a87-a7d03f2592dc.PNG)

Picture 2: Vẫn còn focus
![bug009_2](https://cloud.githubusercontent.com/assets/5047540/18120951/69be617e-6f8c-11e6-9d21-cfdd2c64d389.PNG)

=> Không focus trên line nào sau khi xóa.

**Comment by nhanchuan** [comment]
- Đã fix

**Comment by baonh201092** [comment]
Reviewed OK
