### ISSUE TITLE
[WEB] [BUG] TextBox validation

### ISSUE THREAD

**Issue by baonh201092** [LeDangIUH/Project-FTA#35]
Validate tất cả các Textbox theo những trường hợp sau:
- Null => Nếu là thông tin yêu cầu không null thì  thông báo User nhập, textbox VN yêu cầu thì EN cũng như vậy.
- Giới hạn độ dài
  - Bài Viết: Không giới hạn hoặc 10000 kí tự.
  - TextBox thông thường: 100 kí tự, riêng với Description thì 400 kí tự, User nhập quá giới hạn thì thông báo.
  - Độ dài vượt khỏi textbox thì tránh trường hợp bị bể hay tràn giao diện, có thể cho scroll hoặc xuống dòng.
- Kí tự đặc biệt: textbox nào chứa thông tin mà không được xuất hiện kí tự đặc biệt thì thông báo User.
  Picture: Hình bị vượt range, TextBox EN có thể bị null
  ![bug010](https://cloud.githubusercontent.com/assets/5047540/18121570/6500638c-6f8f-11e6-8b89-8b4997179031.PNG)

**Comment by baonh201092** [comment]
Picture: gần như là bug chung cho các trang, check lại nhá Chuẩn
![bug011](https://cloud.githubusercontent.com/assets/5047540/18121884/f14dea7a-6f90-11e6-9a03-8a55d9e273e8.PNG)

**Comment by baonh201092** [comment]
Picture: Làm tương tự: validation, dịch
![bug031](https://cloud.githubusercontent.com/assets/5047540/18132969/fbdb07ca-6fc2-11e6-8f22-cd099a96a1dd.PNG)

**Comment by nhanchuan** [comment]
- Đã fix

**Comment by baonh201092** [comment]
@nhanchuan text dài quá cho xuống dòng của cell table thôi Chuẩn à, chứ cho scroll ngang bể giao diện, mất mấy button kia, kéo qua ko hay lắm.

**Comment by nhanchuan** [comment]
- Đã fix
  ![image](https://cloud.githubusercontent.com/assets/15918548/18231554/622e9606-72e6-11e6-81ed-ab2dd669ac2a.png)

**Comment by baonh201092** [comment]
@nhanchuan 

# Yêu cầu check lại tất cả những thông tin hiển thị dạng table để fix luôn.

Picture:
![bug021](https://cloud.githubusercontent.com/assets/5047540/18268687/17dfc34e-744f-11e6-8fcd-cf11d75769e5.PNG)

**Comment by nhanchuan** [comment]
- Fix Bảng Chuyên Mục
  ![image](https://cloud.githubusercontent.com/assets/15918548/18272946/0f1ac9c8-7465-11e6-8241-86394f5e1776.png)

**Comment by nhanchuan** [comment]
- Fix bảng danh sách bài viết
  ![image](https://cloud.githubusercontent.com/assets/15918548/18272989/3ed3b878-7465-11e6-8ae4-79aabbc39712.png)

**Comment by nhanchuan** [comment]
- Fix bảng tags
  ![image](https://cloud.githubusercontent.com/assets/15918548/18273090/cc9d6226-7465-11e6-9df4-401184db74d2.png)

**Comment by nhanchuan** [comment]
- Fix bảng Group chat
  ![image](https://cloud.githubusercontent.com/assets/15918548/18273211/72216c24-7466-11e6-8a6b-77b3152094d9.png)

**Comment by nhanchuan** [comment]
- Fix bảng SubSlider
  ![image](https://cloud.githubusercontent.com/assets/15918548/18273313/cfd065b4-7466-11e6-9bec-59a7ff72e3ca.png)

**Comment by nhanchuan** [comment]
- Fix bảng chuyên mục ảnh
  ![image](https://cloud.githubusercontent.com/assets/15918548/18273422/6027b87e-7467-11e6-89c1-87fa556aa242.png)

**Comment by baonh201092** [comment]
Reviewed OK
