### ISSUE TITLE
[BUG] Mất đường hiển thị phân cách giữa 2 line

### ISSUE THREAD

**Issue by baonh201092** [LeDangIUH/Project-FTA#36]
Picture: Bug này có thể sẽ chung nên check luôn cho các trang khác.
![bug012](https://cloud.githubusercontent.com/assets/5047540/18121953/4a38e478-6f91-11e6-8450-98ecbd24ac96.PNG)

**Comment by nhanchuan** [comment]
- Đã fix

**Comment by baonh201092** [comment]
Reviewed OK
