### ISSUE TITLE
[BUG] Vượt hiển thị Menu

### ISSUE THREAD

**Issue by baonh201092** [LeDangIUH/Project-FTA#37]
Giới hạn Độ dài Menu khoảng 20 kí tự, căn chỉnh luôn các trường hợp số lượng menu quá nhiều dẫn đến tình trạng vượt hiển thị (có thể không cho nhập thêm menu hoặc điều chỉnh kích cỡ, hiển thị phù hợp)

Picture 1: ![bug013_1](https://cloud.githubusercontent.com/assets/5047540/18123222/2f9dfe40-6f97-11e6-8408-aee7c2356e24.PNG)

Picture 2:
![bug013](https://cloud.githubusercontent.com/assets/5047540/18123234/3b8d050c-6f97-11e6-9843-d30cfa32d363.PNG)

**Comment by nhanchuan** [comment]
- Đã fix

**Comment by baonh201092** [comment]
Picture: giới hạn số lượng menu tab: 9. lên cái thứ 10 là sẽ tràn.
![bug044](https://cloud.githubusercontent.com/assets/5047540/18225780/e57ad66c-7225-11e6-8605-ca9fce2463b7.PNG)

**Comment by nhanchuan** [comment]
Cho giới hạn 8 mục là OK, không bị vỡ bố cục
![image](https://cloud.githubusercontent.com/assets/15918548/18228117/9a67c458-7268-11e6-88da-4a938a8dc14a.png)

**Comment by baonh201092** [comment]
Reviewed OK
