### ISSUE TITLE
[BUG] System.NullReferenceException: := Object reference not set to an instance of an object. := Stk: at Admin_Pages_MainMenu.btnAddOrtherItem_Click(Object sender, EventArgs e) in c:\inetpub\vhosts\linhkien3h.com\httpdocs\Admin\Pages\MainMenu.aspx.cs:line 438 := Src:App_Web_5hdsmtrv

### ISSUE THREAD

**Issue by baonh201092** [LeDangIUH/Project-FTA#38]
- Block 1: cho xuất hiện giống như các trang khác, có button Chỉnh Sửa rồi mới hiển thị popup.
- Block 2: tương tự chỉ xuất hiện khi được select, nhưng dưới dạng mở rộng.

Picture 1: Lỗi xuất hiện khi chưa select line, mà chọn thêm dữ liệu
![bug014](https://cloud.githubusercontent.com/assets/5047540/18123959/6b92dd96-6f9a-11e6-9f1d-f4fdabe1430f.PNG)

**Comment by nhanchuan** [comment]
- Đã fix

**Comment by baonh201092** [comment]
Reviewed OK
