### ISSUE TITLE
[BUG] Yêu Cầu User nhập Tiêu Đề, Liên Kết cho SubSlider

### ISSUE THREAD

**Issue by baonh201092** [LeDangIUH/Project-FTA#39]
Picture: Cần phải có Tiêu Đề và Liên Kết, SubSlider để người dùng có link nhanh tới nội dung hiển thị nên mất phần link sẽ mất hết ý nghĩa.
![bug015](https://cloud.githubusercontent.com/assets/5047540/18124278/be2a9714-6f9b-11e6-851c-456cc47e5f73.PNG)

**Comment by nhanchuan** [comment]
- Đã fix

**Comment by baonh201092** [comment]
Reviewed OK
