### ISSUE TITLE
[BUG] Thông báo lỗi "Error! System.NullReferenceException: Object reference not set to an instance of an object. at Admin_Pages_Post_New.New_Post_Category_relationships(String postcode) in e:\FTA\Deploy\Thucphamminhbach\Admin\Pages\Post-New.aspx.cs:line 299 at Admin_Pages_Post_New.btnPostNew_Click(Object sender, EventArgs e) in e:\FTA\Deploy\Thucphamminhbach\Admin\Pages\Post-New.aspx.cs:line 480"

### ISSUE THREAD

**Issue by baonh201092** [LeDangIUH/Project-FTA#4]
1/ Login trang Admin (User = admin, pass = zxcvbnm)
2/ Click [Bài Viết] -> click [Viết Bài Mới]
3/ Nhập Tile: "Bài Viết Mới", Nội Dung: "Example"
4/ Click [Chuyên mục] -> Click [Tin Tức] -> Click [Đăng Bài Viết]
==> Báo Lỗi "Error! System.NullReferenceException: Object reference not set to an instance of an object. at Admin_Pages_Post_New.New_Post_Category_relationships(String postcode) in e:\FTA\Deploy\Thucphamminhbach\Admin\Pages\Post-New.aspx.cs:line 299 at Admin_Pages_Post_New.btnPostNew_Click(Object sender, EventArgs e) in e:\FTA\Deploy\Thucphamminhbach\Admin\Pages\Post-New.aspx.cs:line 480"

Picture:
![bug015](https://cloud.githubusercontent.com/assets/5047540/17835911/da804ce0-67aa-11e6-862e-631e0b32715f.png)

**Comment by nhanchuan** [comment]
1/ Login trang http://linhkien3h.com/Admin/Pages/Post-New.aspx (User = admin, pass = zxcvbnm)
2/ Click [Bài Viết] -> click [Viết Bài Mới]
3/ Nhập Tile: "KIỂM TRA TÍNH NĂNG VIẾT BÀI", Nội Dung: "KIỂM TRA TÍNH NĂNG VIẾT BÀI - NỘI DUNG"
4/ Click [Chuyên mục] -> Click [Tin Tức] -> Click [Đăng Bài Viết]

**Comment by baonh201092** [comment]
Close Bug, chuyển sang Bug #3
