### ISSUE TITLE
[WEB] [BUG] Click [New User] => page not found

### ISSUE THREAD

**Issue by baonh201092** [LeDangIUH/Project-FTA#40]
Picture:
![bug016](https://cloud.githubusercontent.com/assets/5047540/18124428/622a6222-6f9c-11e6-9303-bb3c0379f8cc.PNG)

**Comment by nhanchuan** [comment]
Không điền thông tin mặc định khi tạo User ?

**Comment by baonh201092** [comment]
Fill Họ, Mật khẩu hiện thông tin mặc định như hình
Cái này do máy t lưu cookie nên bị.

**Comment by baonh201092** [comment]
Picture 1: Click [New User]
![bug039](https://cloud.githubusercontent.com/assets/5047540/18192917/b25d1b88-7102-11e6-888b-e8dcb8752352.PNG)
Picture 2:
![bug039_1](https://cloud.githubusercontent.com/assets/5047540/18192932/cfbde360-7102-11e6-8ea7-ebe3fc2d6b7d.PNG)

**Comment by nhanchuan** [comment]
- Đã fix

**Comment by baonh201092** [comment]
Picture 1: Thêm con tương tự. Click [Chuyên Mục]
![bug041](https://cloud.githubusercontent.com/assets/5047540/18225438/b08a16e8-721b-11e6-9b24-b72202224c13.PNG)

Picture 2:
![bug041_1](https://cloud.githubusercontent.com/assets/5047540/18225441/bc3da004-721b-11e6-863f-5ab338b0f13b.PNG)

**Comment by nhanchuan** [comment]
-- Fix rồi.. truy cập Page OK

**Comment by baonh201092** [comment]
@nhanchuan . Check lại đi Chuẩn, vẫn còn đấy

**Comment by baonh201092** [comment]
@nhanchuan , trên máy t vẫn còn. Xóa cache, check các kiểu nhưng link vẫn thế.

**Comment by nhanchuan** [comment]
@LeDangIUH  access Link này thử : http://linhkien3h.com/Admin/Pages/Category.aspx
user : admin
pass: zxcvbnm

**Comment by nhanchuan** [comment]
- There is no test for a long time what that means is adopted.

**Comment by baonh201092** [comment]
@nhanchuan Check lại bằng máy khác thử bug này đi Chuẩn. Link nó cứ bị double Admin thôi.
