### ISSUE TITLE
[BUG] Danh sách hình ảnh duyệt từ máy chủ không giống với danh sách trong thư viện

### ISSUE THREAD

**Issue by baonh201092** [LeDangIUH/Project-FTA#42]
Picture 1: duyệt trên máy chủ
![bug034](https://cloud.githubusercontent.com/assets/5047540/18136383/6144ec32-6fcf-11e6-9ecd-3fb5bd409199.PNG)

Picture 2: ảnh trong thư viện
![bug034_1](https://cloud.githubusercontent.com/assets/5047540/18136927/afff64dc-6fd0-11e6-9f58-15c546a956a4.PNG)

**Comment by nhanchuan** [comment]
- Đã fix

**Comment by baonh201092** [comment]
Danh sách hình vẫn chưa có gì thay đổi, vẫn chưa tương ứng với danh sách hình ảnh trong thư viện.

**Comment by nhanchuan** [comment]
- Hình ảnh duyệt từ máy chủ là tui làm cho bài posts, không nhất thiết phải lấy toàn bộ ảnh trong thư viện. Còn nếu người dùng muốn lấy ảnh khác từ thư viện thì chỉ cần mở tab thư viện copy link và paste vào là được.

**Comment by baonh201092** [comment]
làm vậy phiền quá ko, khi đã duyệt từ máy chủ là nó chỉ cần list tất cả hình ảnh có sẵn trên máy chủ thôi. User đâu ai biết phải làm rắc rối vậy

**Comment by nhanchuan** [comment]
- User chỉ cần lấy chính xác những Images của bài post thôi. Những images khác không liên quan.., còn nếu như muốn lấy thì qua kia copy link. Như vậy đâu có gi là rắc rối.. còn dễ hơn cả sử dụng MS Word.

**Comment by baonh201092** [comment]
Ok.
