### ISSUE TITLE
[WEB] [BUG] Hiện lịch Đăng Bài Không Chính Xác.

### ISSUE THREAD

**Issue by baonh201092** [LeDangIUH/Project-FTA#43]
Picture: Hẹn giờ 11h30 nhưng 11h26 đã thấy Đăng Bài
![bug038](https://cloud.githubusercontent.com/assets/5047540/18192654/7a61f9ee-7100-11e6-84c1-0f0473372d40.PNG)

**Comment by nhanchuan** [comment]
- Đã Test : Sỡ dĩ có sự lệch chút time là do Bài POst lấy time của server . Còn trong bài test là theo time của client. Time của server có thể khác time của client phụ thuộc vào vị trí đặt server .

**Comment by baonh201092** [comment]
Picture: Chọn 10h nhưng click ok vẫn hiện thời gian hệ thống, nếu chỉ lấy thời gian Đăng hiện tại thôi, không phải hẹn giờ đăng thì cần bỏ đi. Lấy mặc định hệ thống giờ đăng bài.
![bug040](https://cloud.githubusercontent.com/assets/5047540/18225372/e090a8a8-721a-11e6-813b-c3c4f84d1a40.PNG)

**Comment by nhanchuan** [comment]
- Vừa fix lại..
  - Có thể thời gian lệch múi giờ với sever hơn 8 tiếng, nếu test thì lấy time hơn 8h test cho chack

**Comment by baonh201092** [comment]
@LeDangIUH report dùm chính xác giờ server vs giờ của client là bao nhiêu để test Đăng.
