### ISSUE TITLE
[Q&A] Làm sao thay đổi được hình ảnh User Profile

### ISSUE THREAD

**Issue by baonh201092** [LeDangIUH/Project-FTA#44]
Picture:
![bug042](https://cloud.githubusercontent.com/assets/5047540/18225548/b30989dc-721e-11e6-96d8-9426686a4292.PNG)

**Comment by nhanchuan** [comment]
- cứ vậy đi,, khi nào update version 2.0 thì sẽ có.

**Comment by baonh201092** [comment]
uhm, vậy thì note lại để đó

**Comment by baonh201092** [comment]
Closed. Implement tại version sau.
