### ISSUE TITLE
[BUG] Yêu cầu User Nhập [Tên Menu(EN)]

### ISSUE THREAD

**Issue by baonh201092** [LeDangIUH/Project-FTA#45]
Picture:
![bug046](https://cloud.githubusercontent.com/assets/5047540/18231169/5db83a1a-72db-11e6-986c-0f1b6d17639e.PNG)

**Comment by nhanchuan** [comment]
- Đã fix.
  ![image](https://cloud.githubusercontent.com/assets/15918548/18231477/c46ed7ec-72e4-11e6-8794-82c6e0459a07.png)

**Comment by baonh201092** [comment]
Reviewed OK
