### ISSUE TITLE
[WEB] Banner và header có khoảng cách

### ISSUE THREAD

**Issue by LeDangIUH** [LeDangIUH/Project-FTA#47]
Cần check lại các banner 

![untitled](https://cloud.githubusercontent.com/assets/3908468/18232565/fe4e822a-72fb-11e6-8ca6-1233a0c2bf3d.png)

**Comment by nhanchuan** [comment]
- Đã fix 
  ![image](https://cloud.githubusercontent.com/assets/15918548/18235795/6a9777fa-7349-11e6-945f-54305a264603.png)

**Comment by LeDangIUH** [comment]
Done
