### ISSUE TITLE
[WEB] Thay banner thứ 3 

### ISSUE THREAD

**Issue by LeDangIUH** [LeDangIUH/Project-FTA#48]
Từ 
![image](https://cloud.githubusercontent.com/assets/3908468/18232845/a412f8a2-7302-11e6-9e8a-465ee731661a.png)

Thành

![image](https://cloud.githubusercontent.com/assets/3908468/18232841/969af26a-7302-11e6-9110-49bf4ea66867.png)

Chỉ thay đổi hình nền chữ vẫn vậy nhé và chú ý hình gốc là giao diện của mobile người ta thì co gắng thay đổi lại cho logo minh vào giống như sheet '2' làm cho đẹp lại

**Comment by nhanchuan** [comment]
- Đã fix
  Review at linhkien3h.com

**Comment by LeDangIUH** [comment]
Done
