### ISSUE TITLE
[WEB] Lỗi ngôn ngữ

### ISSUE THREAD

**Issue by LeDangIUH** [LeDangIUH/Project-FTA#49]
Tạo tài khoản xong là toàn tiếng anh trong khi đó tôi đang tiếng việt

![image](https://cloud.githubusercontent.com/assets/3908468/18232915/0ab085ba-7304-11e6-801c-d88ea431d02c.png)

Tiếng anh việt lộn xộn.
cả giao diện nữa

**Comment by nhanchuan** [comment]
- ĐÃ FIX
  ![image](https://cloud.githubusercontent.com/assets/15918548/18236020/12f30cdc-734c-11e6-9838-143cc192d122.png)

**Comment by baonh201092** [comment]
Reviewed OK
