### ISSUE TITLE
[BUG] Textbox kéo vượt range

### ISSUE THREAD

**Issue by baonh201092** [LeDangIUH/Project-FTA#5]
1/ Login trang Admin (User = admin, pass = zxcvbnm)
2/ Click [Bài Viết] -> Click [Viết Bài Mới] -> Click [Meta Tags] -> Click góc phải [Meta Description], kéo thả
==> Có thể kéo thả tự do.

Nên tham khảo phần Write của Github. Có thể làm giống tương tự.
# **\* Fix luôn những textbox tương tự.**

Picture:
![bug016](https://cloud.githubusercontent.com/assets/5047540/17836125/a152228e-67b1-11e6-8984-f8f8679e755e.PNG)

**Comment by baonh201092** [comment]
Cho lí do cụ thể nha @nhanchuan . Do tui thấy là kéo đi vô tư thế sẽ bể giao diện, 1 là fix, 2 là kéo như github là được

**Comment by nhanchuan** [comment]
- Đã fix szie

**Comment by nhanchuan** [comment]
Checking at http://linhkien3h.com/lien-he

**Comment by baonh201092** [comment]
Check kỹ lại những chỗ có sử dụng textbox như thế này. Vẫn còn nha @nhanchuan

**Comment by nhanchuan** [comment]
*\* Đã fix toàn bộ các textbox  with Mode MultiLine or Textarea 
==> checking at http://linhkien3h.com/admin/
accout login : admin
password : zxcvbnm

**Comment by baonh201092** [comment]
Vẫn còn textbox của bài viết nha @nhanchuan

**Comment by nhanchuan** [comment]
*\* Đã fix toàn bộ các textbox with Mode MultiLine or Textarea trong bài viết và update bài viết
==> checking at http://linhkien3h.com/admin/
accout login : admin
password : zxcvbnm

**Comment by baonh201092** [comment]
Reviewed OK
