### ISSUE TITLE
[WEB] Login ko duoc

### ISSUE THREAD

**Issue by LeDangIUH** [LeDangIUH/Project-FTA#50]
Ngay sao bước thành công đăng kí --> nhấp ngay login -->

![image](https://cloud.githubusercontent.com/assets/3908468/18232931/56a6a684-7304-11e6-928e-e9178cc0f7c6.png)

Không chay duoc, ngon ngu cung la tieng anh.

**Comment by nhanchuan** [comment]
- Bug này liên quan tới #49 . Đã được FIX.
  Còn Login không được là chưa vào mail của mình kích hoạt, thì không login dc là đúng rồi.

**Comment by baonh201092** [comment]
Closed
