### ISSUE TITLE
[WEB] Lỗi mã kích hoat ko hop le

### ISSUE THREAD

**Issue by LeDangIUH** [LeDangIUH/Project-FTA#51]
Sau khi kich hoat tài khoản --> cũng đang trang kích hoạt --> nhấp đăng nhập --> đăng nhập thành công --> hien mã kích hoạch ko hop lệ.

Phải hiện trang chủ chứ.

![image](https://cloud.githubusercontent.com/assets/3908468/18232939/aa38aa36-7304-11e6-97dd-2c69a3ae9b99.png)

**Comment by nhanchuan** [comment]
- Event này sẽ bắt: nếu kích hoạt thành công thì khi đăng nhập sẽ chuyển về trang chủ nhé.

**Comment by nhanchuan** [comment]
- Đã FIX

**Comment by baonh201092** [comment]
Reviewed OK.
