### ISSUE TITLE
[WEB] Không thống nhất

### ISSUE THREAD

**Issue by LeDangIUH** [LeDangIUH/Project-FTA#53]
![image](https://cloud.githubusercontent.com/assets/3908468/18233152/93f30258-7309-11e6-8f91-c5a6ebb57018.png)

vì sao Trach nhiem xã hội và cơ hội nghề nghiiep thì thuoc bài viết có share face, like riêng 2 cái lich sử hình thành và đôi ngu chuyen gia thì nam trong menu

**Comment by nhanchuan** [comment]
- 2 trang Lịch sử hình thành và đội ngủ phát triển là pages design . Còn các trang kia là post design.
- pages thì nó cố định nội dung trên nền html lun. 
- post thì cho admin vào edit lại, tùy thuộc vào nội dung có thể update.
