### ISSUE TITLE
[ADMIN SITE] Load hinh mac đinh khi nang cap tai khoan

### ISSUE THREAD

**Issue by LeDangIUH** [LeDangIUH/Project-FTA#56]
![image](https://cloud.githubusercontent.com/assets/3908468/18233456/13839eb2-7312-11e6-983c-662b92b267c9.png)

Trường hop khi user5 đăng kí ban đầu nêu nguoi ta có chon hinh dai dien thi lấy hinh đó làm defaul khi load lên ban đầu khi nâng cấp tài khoàn, cho phép ho thay đổi nhé.

**Comment by baonh201092** [comment]
Reviewed OK.
