### ISSUE TITLE
[ADMIN SITE] chua hiện hình dai dien khi chon

### ISSUE THREAD

**Issue by LeDangIUH** [LeDangIUH/Project-FTA#57]
![image](https://cloud.githubusercontent.com/assets/3908468/18233464/5c8b988a-7312-11e6-99af-d6b04efac6d4.png)

nang cấp tai khoan chọn hình chua thấy hiện,,,có khi nào permisstion chua thiết lap

**Comment by baonh201092** [comment]
Reviewed OK
