### ISSUE TITLE
[ADMIN SITE] Hình sản phẩm và thông tin minh bạch không load lại

### ISSUE THREAD

**Issue by khaiho2002** [LeDangIUH/Project-FTA#63]
Ở trang chỉnh sửa sản phẩm của user4, khi chọn hình ảnh sản phẩm và hình ở thông tin minh bạch. Hình không tự load lại ở khung image.
![issue_load_image](https://cloud.githubusercontent.com/assets/11847266/18279868/3fd8eac4-7481-11e6-8c9c-6a974009cc3f.PNG)

**Comment by baonh201092** [comment]
Reviewed OK.
Load ảnh ngay lập tức.
