### ISSUE TITLE
[ADMIN SITE] Load lại notification khi lưu thành công ở trang chỉnh sửa sản phẩm user4

### ISSUE THREAD

**Issue by khaiho2002** [LeDangIUH/Project-FTA#64]
![issue_show_notify](https://cloud.githubusercontent.com/assets/11847266/18280274/b77963dc-7482-11e6-995b-55cdabcb5076.PNG)
Đổi kiểu hiển thị của notify khi lưu chỉnh sửa sản phẩm thành công như hình bên dưới.
![issue_show_notify_1](https://cloud.githubusercontent.com/assets/11847266/18280433/29cea53c-7483-11e6-814e-6d690a2277c7.PNG)

**Comment by baonh201092** [comment]
Reviewed OK
