### ISSUE TITLE
[WEB] Hiển thị nội dung bài viết bị tràn

### ISSUE THREAD

**Issue by baonh201092** [LeDangIUH/Project-FTA#65]
Picture:
![bug048](https://cloud.githubusercontent.com/assets/5047540/18280528/81017000-7483-11e6-8240-9c63600ca5c2.PNG)

**Comment by nhanchuan** [comment]
- Lỗi do viết không cách , không ngắt câu. 
- Cái này hơi bất hợp lý xíu. KHÔNG Tồn tại văn bản nào vượt quá 100 ký tự mà không dấu cách hoặc ngắt dòng.....
- @baonh201092  có cao kiến gi xin chỉ giáo .

**Comment by baonh201092** [comment]
Do phần content nằm ở panel giữa rồi, nên không được vượt ra panel ngoài. Nếu vượt theo kiểu này thì cứ đưa ra giải thuật chẳng hạn:
- Cho tự xuống dòng tại khoảng trắng cuối cùng trong chuỗi 100 (Tùy theo kích thước content mà config) kí tự.
- Cho tự xuống dòng tại kí tự 100 (Tùy theo kích thước content mà config) nếu chuỗi liền. Cái này phải chấp nhận vậy thôi.

**Comment by baonh201092** [comment]
Reviewed OK
