### ISSUE TITLE
[WEB] Căn chỉnh giao diện

### ISSUE THREAD

**Issue by baonh201092** [LeDangIUH/Project-FTA#67]
Picture:
![bug002](https://cloud.githubusercontent.com/assets/5047540/18282497/8cde5958-748b-11e6-822b-54d7476be579.PNG)

**Comment by nhanchuan** [comment]
- Đã Fix 
  ![image](https://cloud.githubusercontent.com/assets/15918548/18282769/cc2230a2-748c-11e6-88a7-94ce52396c86.png)

**Comment by baonh201092** [comment]
Reviewed OK
