### ISSUE TITLE
[WEB] Hiển thị tiếng Việt tại mode tiếng Anh

### ISSUE THREAD

**Issue by baonh201092** [LeDangIUH/Project-FTA#69]
- Tag ở Trang chủ là "Sự Kiện" nhưng sang trang chi tiết là "Event" tại mode tiếng Anh.

Picture 1:
![bug005_1](https://cloud.githubusercontent.com/assets/5047540/18283776/1fc18592-7491-11e6-89ca-e177f95c9352.PNG)

Pciture 2:
![bug005_2](https://cloud.githubusercontent.com/assets/5047540/18283779/2348a4ca-7491-11e6-9846-fe8717b3b24f.PNG)

**Comment by nhanchuan** [comment]
- Nội dung bài bằng Tiếng Anh không được người viết bài bằng Tiếng Anh mà viết BQngf Tiết Việt lun.

**Comment by baonh201092** [comment]
Reviewed OK
