### ISSUE TITLE
[WEB] Nội dung Việt/Anh không tương đối, bài tiếng Anh thiếu link liên kết.

### ISSUE THREAD

**Issue by baonh201092** [LeDangIUH/Project-FTA#72]
Picture 1:
![bug007_1](https://cloud.githubusercontent.com/assets/5047540/18284031/756de674-7492-11e6-9968-49decd97189c.png)

Picture 2:
![bug007_2](https://cloud.githubusercontent.com/assets/5047540/18284039/7a057be8-7492-11e6-8913-19caf816db87.PNG)

**Comment by baonh201092** [comment]
@nhanchuan Check lại các bài khác mà nội dung EN chưa được update lại.

**Comment by nhanchuan** [comment]
- Phần này cho Biên tập viên post bài. 
- Nội dung các Post sau khi release sẽ clear.

**Comment by nhanchuan** [comment]
- các post và nội dung post hiện chỉ mang tính chất Demo

**Comment by baonh201092** [comment]
Closed
