### ISSUE TITLE
[ADMIN SITE] Không hiển thị tên sản phẩm

### ISSUE THREAD

**Issue by khaiho2002** [LeDangIUH/Project-FTA#73]
Không hiển thị tên sản phẩm trong trang "Sản phẩm yêu thích của user5".
![issue_01](https://cloud.githubusercontent.com/assets/11847266/18297554/a8de2e1c-74db-11e6-87d7-d8418c57f8d2.PNG)

**Comment by baonh201092** [comment]
Reviewed OK.
Hiển thị link tới sản phẩm
