### ISSUE TITLE
[ADMIN SITE] Tìm kiếm sản phẩm

### ISSUE THREAD

**Issue by khaiho2002** [LeDangIUH/Project-FTA#74]
Không thể tìm kiếm sản phẩm từ thanh tìm kiếm.
![issue_02_01](https://cloud.githubusercontent.com/assets/11847266/18297585/eca9205c-74db-11e6-9649-9ea605546dc0.PNG)
![issue_02_02](https://cloud.githubusercontent.com/assets/11847266/18297586/ee705856-74db-11e6-8b8a-aa09b3d17f54.PNG)

**Comment by baonh201092** [comment]
@khaiho2002 
Hiện tại tìm kiếm chính xác chỉ tạm ổn thôi chứ chưa đáp ứng được nhu cầu.
Nên sẽ add thêm label để cập nhật sau.
