### ISSUE TITLE
[ADMIN SITE] Không hiển thị hình profile của User

### ISSUE THREAD

**Issue by khaiho2002** [LeDangIUH/Project-FTA#75]
![Uploading issue_03.PNG…]()

**Comment by khaiho2002** [comment]
![issue_03](https://cloud.githubusercontent.com/assets/11847266/18298348/1461d5e8-74e2-11e6-8259-e893473c78d4.PNG)

**Comment by LeDangIUH** [comment]
@vdhung kiem tra lai nào

**Comment by lyquoclam** [comment]
Anh Khai, khi user thay đổi picture and nhấn nút Lưu sau đó Hình Ảnh trên profile đó mới được load hình ảnh mới. Không phải chọn file là thay đổi hình ảnh của profile liền được @khaiho2002

**Comment by khaiho2002** [comment]
Confirm: phải sign-out rồi log-in lại rồi sẽ change

**Comment by baonh201092** [comment]
Reviewed OK.
Hiển thị đồng bộ hình ảnh User
