### ISSUE TITLE
[WEB] Textbox Validation cho phần edit giống như add new

### ISSUE THREAD

**Issue by baonh201092** [LeDangIUH/Project-FTA#76]
@nhanchuan 
# Check luôn cho các phần edit khác nữa.

VD:
- Độ dài: 50 kí tự, ##check null nếu User update thành null.

Picture:
![bug022](https://cloud.githubusercontent.com/assets/5047540/18299129/972b1a9c-74e8-11e6-955d-364d212f8fbd.PNG)

**Comment by nhanchuan** [comment]
- Đã fix cho toàn bộ

**Comment by baonh201092** [comment]
Vẫn còn phần Chỉnh Sửa bên Cài Đặt => Cài Đặt Menu
Cái này click vào nó mất dialog và kẹt luôn
