### ISSUE TITLE
[WEB] "Mô Tả Ngắn (VN - EN)" giới hạn độ dài để tránh vượt database

### ISSUE THREAD

**Issue by baonh201092** [LeDangIUH/Project-FTA#77]
Picture: Giới hạn độ dài textbox khoảng 400 kí tự hoặc tùy theo định nghĩa trong database để tránh vượt lưu dữ liệu
![bug023](https://cloud.githubusercontent.com/assets/5047540/18302701/7071f16c-7503-11e6-898a-b390e32be8f7.PNG)

**Comment by nhanchuan** [comment]
- Đã fix

**Comment by baonh201092** [comment]
Reviewed OK
