### ISSUE TITLE
[WEB] Tải và Cập Nhật Hình Ảnh không chính xác

### ISSUE THREAD

**Issue by baonh201092** [LeDangIUH/Project-FTA#79]
Sau khi tải và cập nhật hình ảnh đều không được.

Picture 1:
![bug025](https://cloud.githubusercontent.com/assets/5047540/18302994/055d62ce-7505-11e6-9d81-e8d3a5a10180.PNG)

Picture 2:
![bug025_1](https://cloud.githubusercontent.com/assets/5047540/18302998/09199ef0-7505-11e6-906e-18834ca8b3e0.PNG)

**Comment by nhanchuan** [comment]
@baonh201092  Test lại lần nữa thử.

**Comment by nhanchuan** [comment]
- Vẫn update hình dc mà.

**Comment by nhanchuan** [comment]
- Updated.

**Comment by baonh201092** [comment]
Reviewed OK
