### ISSUE TITLE
[WEB] Chính Sách Bảo Mật, Điều Khoản Dịch Vụ hiển thị ở đâu trên trang chủ ?

### ISSUE THREAD

**Issue by baonh201092** [LeDangIUH/Project-FTA#80]
Picture:
![bug026](https://cloud.githubusercontent.com/assets/5047540/18304475/cbf0a660-750c-11e6-9f4b-40318c237b97.PNG)

**Comment by nhanchuan** [comment]
- Here 
  ![image](https://cloud.githubusercontent.com/assets/15918548/18305071/01535714-7510-11e6-9a8b-afa379a77934.png)

**Comment by baonh201092** [comment]
Close
