### ISSUE TITLE
[WEB] Web die khi nhập nội dung "<html lang="en"> <head> <meta http-equiv=" vào textbox

### ISSUE THREAD

**Issue by baonh201092** [LeDangIUH/Project-FTA#82]
@nhanchuan 
Fix luôn tất cả các textbox còn lại. Khá là nhiều
Picture:
![bug028](https://cloud.githubusercontent.com/assets/5047540/18306121/976e24a0-7514-11e6-9e20-75c34b4280e2.PNG)

**Comment by nhanchuan** [comment]
@baonh201092  Có giải pháp Validate gi không,, tại vì mình nhập là Tiếng Việt. không thể chặn các ký tự dấu được.

**Comment by baonh201092** [comment]
@nhanchuan Tìm công thức regrex apply cho nó chẳng hạn Chuẩn.
http://stackoverflow.com/questions/5885017/restricting-user-entering-html-tag-in-textbox-using-validation-control-in-asp-ne

**Comment by baonh201092** [comment]
@lyquoclam . hỗ trợ Chuẩn phần này, fix giống bên FTA cũng được.

**Comment by lyquoclam** [comment]
Hi Anh @baonh201092  và @nhanchuan 
 sử dụng code này 

function replaceData(str) {
            if (str == null || str == undefined)
                return '';
            var newStr = str.replace('"', '');
            newStr = newStr.replace("'", '');
            newStr = newStr.replace("<", '');
            newStr = newStr.replace(">", '');
            if (newStr.indexOf('"') >= 0 || newStr.indexOf("'") >= 0 || newStr.indexOf("<") >= 0 || newStr.indexOf(">") >= 0)
                return replaceData(newStr);
            return newStr;
        }
