### ISSUE TITLE
[ADMIN SITE] Chứng thực của hồ sơ đăng ký không tự load lại

### ISSUE THREAD

**Issue by khaiho2002** [LeDangIUH/Project-FTA#85]
Đối với hồ sơ đăng ký đã duyệt. Khi admin chọn chức năng xem lại.
Các chứng thực không tự load lại các tên chứng thực đã chọn trước đó.
![issue_01_01](https://cloud.githubusercontent.com/assets/11847266/18321602/d0f43d1a-7558-11e6-9a2c-45232f19b24b.PNG)
![issue_01_02](https://cloud.githubusercontent.com/assets/11847266/18321601/d0efd608-7558-11e6-948e-68c170bc873c.PNG)

**Comment by baonh201092** [comment]
Reviewed OK.
Hiển thị chứng nhận ok
