### ISSUE TITLE
[ADMIN SITE] Lịch sử tra cứu user5

### ISSUE THREAD

**Issue by khaiho2002** [LeDangIUH/Project-FTA#88]
Chức năng "Lịch sử tra cứu" của user5 chưa hoạt động.
Khi click vào tên sản phẩm. Sản phẩm không xuất hiện trong trang "Lịch sử tra cứu".

**Comment by khaiho2002** [comment]
Fix in Revision #511

**Comment by baonh201092** [comment]
Reviewed OK.
 Hiển thị được lịch sử tra cứu
