### ISSUE TITLE
[ADMIN SITE] Tạm dừng nhóm sản phẩm

### ISSUE THREAD

**Issue by khaiho2002** [LeDangIUH/Project-FTA#89]
Khi admin tạm dừng nhóm sản phẩm. 
- User5
- Sản phẩm của nhóm đó không được xuất hiện trong trang chủ, lịch sử tìm kiếm, sản phẩm yêu thích của user5.
- Khi nâng cấp tài khoản, thêm sản phẩm --> Không được cho user chọn nhóm sản phẩm đã tạm dừng.
- User4
- Khi yêu cầu sản phẩm mới -> Không được cho user chọn nhóm sản phẩm đã tạm dừng.

**Comment by khaiho2002** [comment]
Kiểm tra thêm chỗ quản lý nhóm minh bạch của trang "Tài khoản giám sát, Tài khoản quản trị". Không được load nhưng nhóm sản phẩm đã bị tạm dừng.

**Comment by lyquoclam** [comment]
Fixed Revision: #520

**Comment by baonh201092** [comment]
Reviewed OK.
Đã check các thông tin liên quan.
