### ISSUE TITLE
[BUG] Không xóa được Menu item

### ISSUE THREAD

**Issue by baonh201092** [LeDangIUH/Project-FTA#9]
1/ Login trang Admin (User = admin, pass = zxcvbnm)
2/ Click [Setting] ->  [Menu Setting]
3/ Click [Select] 1 Menu Item -> Delete
=> Không xóa được

Picture:
![bug020](https://cloud.githubusercontent.com/assets/5047540/17837838/11933ac0-67e8-11e6-9273-f5e3095cd71a.PNG)

**Comment by nhanchuan** [comment]
1/ Login trang http://linhkien3h.com/Admin/Pages/MainMenu.aspx (User = admin, pass = zxcvbnm)
2/ Click [Setting] -> [Menu Setting]
3/ Click [Select] 1 Menu Item -> Delete

Result => Đã bổ sung tính năng xóa Menu Item

**Comment by baonh201092** [comment]
Reviewed OK
