### ISSUE TITLE
[ADMIN SITE] Chưa load chứng nhận cho chi tiết công ty

### ISSUE THREAD

**Issue by khaiho2002** [LeDangIUH/Project-FTA#91]
Cần show thêm công ty có những chứng nhận nào khi click vào chi tiết công ty theo đường link:
http://admin.thucphamminhbach.org/Company/Info/4

**Comment by lyquoclam** [comment]
Fixed at Revision #517

**Comment by baonh201092** [comment]
Reviewed OK
