### ISSUE TITLE
[ADMIN SITE] Cho phép phóng to hình ảnh

### ISSUE THREAD

**Issue by khaiho2002** [LeDangIUH/Project-FTA#92]
Thêm chức năng phóng to hình ảnh của logo sản phẩm, logo công ty, file đính kèm chứng thực, logo chứng thực, logo user.

**Comment by khaiho2002** [comment]
Fixed in revision #518

**Comment by baonh201092** [comment]
Vẫn còn xót chưa phóng to hết.
Cần check lại toàn bộ.

@lyquoclam Vào xử luôn đi em.
VD:
![bug025](https://cloud.githubusercontent.com/assets/5047540/18682916/4ce203c8-7f98-11e6-848c-3bd4a64a4b90.PNG)

**Comment by baonh201092** [comment]
Reviewed OK
