### ISSUE TITLE
Nhóm ko có Avatar.. Xóa Img default, Logo cty change chưa??

### ISSUE THREAD

**Issue by vdhung** [LeDangIUH/Project-FTA#93]
![aaaaaaaaaaaa](https://cloud.githubusercontent.com/assets/6865149/18418731/ea8ef312-7875-11e6-909e-5736ce5a0426.PNG)

**Comment by vdhung** [comment]
@lyquoclam @khaiho2002

**Comment by lyquoclam** [comment]
Fixed at Revision #528
