### ISSUE TITLE
[ADMIN SITE] Chưa thực hiện textbox validation chính xác

### ISSUE THREAD

**Issue by baonh201092** [LeDangIUH/Project-FTA#98]
Step:
1/ Đăng Nhập FTA bằng account spadmin - xxx.
2/ Click User -> Hồ Sơ Cá Nhân.
3/ Chỉnh sửa Textbox [Điện Thoại], [Ngày Sinh] như hình.
4/ Click Lưu.

Suggestion:
1/ Textbox [Điện Thoại]:
- Chỉ cho nhập kí tự '+' và số [0-9]. Vd: +84904944474 = 0904944474.
- Giới hạn độ dài 20
  2/ Box [Ngày Sinh]:
- Check ngày hợp lệ nếu User nhập tay.

Picture: 
![bug001](https://cloud.githubusercontent.com/assets/5047540/18482294/c3d87d7a-7a09-11e6-80a2-b0a02bb78694.PNG)

**Comment by lyquoclam** [comment]
Số điện thoại: max length(15) ko cần +84
Ngày Sinh: max leng5th(10) 

**Note:** Test lại sau bản build 3h ngày 19/8 vậy đó

**Comment by baonh201092** [comment]
Chuyển message về tiếng Việt luôn cho đồng bộ đi @lyquoclam.
 xóa số thêm chữ là ra bug.
Picture:
![bug026](https://cloud.githubusercontent.com/assets/5047540/18683272/c2893f32-7f99-11e6-8d18-2216aa066112.png)

**Comment by lyquoclam** [comment]
Fixed đợi build anh Dang ngày 23/9

**Comment by baonh201092** [comment]
Reviewed OK
