### ISSUE TITLE
[ADMIN SITE] Tải ảnh lên chưa chính xác

### ISSUE THREAD

**Issue by baonh201092** [LeDangIUH/Project-FTA#99]
Step
1/ Đăng Nhập FTA bằng account spadmin - xxx.
2/ Click User -> Hồ Sơ Cá Nhân.
3/ Upload file Explorer.exe
4/ Click Lưu.

Suggestion:
- Chức năng tải ảnh chỉ chấp nhận tải lên các file có định dạng ảnh.
- Dung lượng <= 4mb.

Picture 1:
![bug002](https://cloud.githubusercontent.com/assets/5047540/18482919/3d480c46-7a0c-11e6-8a37-b88f610fc9ae.PNG)

Picture 2:
![bug002_1](https://cloud.githubusercontent.com/assets/5047540/18482933/5381d10e-7a0c-11e6-91df-f7a073957d83.PNG)

**Comment by baonh201092** [comment]
@vdhung Check lại con này cái Hưng ơi.
Hiện tại upload khác file ảnh thì OK rồi. Nhưng nó báo email đã tồn tại có vẻ không liên quan.
==> Nếu upload ảnh không thành công (do lỗi hay ko phải file ảnh thì thông báo thôi).

**Comment by lyquoclam** [comment]
HI Anh @baonh201092 
Hiện tai khi click Lưu nó báo "Email đã tồn tại" là lỗi data Em đã sửa database lại.

**Comment by baonh201092** [comment]
bug vẫn còn nhá.
Upload file exe vẫn được. Đặc biệt file exe nặng phải chờ upload rất lâu
=> chưa giới hạn dung lượng file 4mb, chưa lọc chỉ cho upload file ảnh.

**Comment by lyquoclam** [comment]
Hi Anh @baonh201092 
Anh bảo em đâu chọn dc file exe dau, ảnh check lại xem

**Comment by baonh201092** [comment]
@lyquoclam Chuyển qua All File là chọn dc r, có 2 lưa chọn custom file và All File mà. Ko remove dc All File thì phải check input thôi.

**Comment by lyquoclam** [comment]
Em đã thêm validation cho chọn file. Đợi build 25/9
